### ISSUE TITLE
v6.8.0 appears in npm but not in releases

### ISSUE THREAD

**Issue by elektronik2k5** [mobxjs/mobx#3630] opened 2023-02-11 07:50 UTC
**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Versions**

Here's the npm release:
```shell
 ❯ npm info mobx@6.8.0                             
npm WARN Ignoring workspaces for specified package(s) 
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠧ : WARN Ignoring workspaces for specified package(s)
mobx@6.8.0 | MIT | deps: none | versions: 233
Simple, scalable state management.
https://mobx.js.org/

keywords: mobx, mobservable, observable, react-component, react, reactjs, reactive, model, frp, functional-reactive-programming, state management, data flow

dist
.tarball: https://registry.npmjs.org/mobx/-/mobx-6.8.0.tgz
.shasum: 59051755fdb5c8a9f3f2e0a9b6abaf86bab7f843
.integrity: sha512-+o/DrHa4zykFMSKfS8Z+CPSEg5LW9tSNGTuN8o6MF1GKxlfkSHSeJn5UtgxvPkGgaouplnrLXCF+duAsmm6FHQ==
.unpackedSize: 4.0 MB

maintainers:
- fredyc <fredy.c@seznam.cz>
- mweststrate <mweststrate@gmail.com>
- capaj <capajj@gmail.com>
- jilles <login@jilles.me>
- andykog <mail@andykog.com>
- xaviergonz <xaviergonz@gmail.com>

dist-tags:
beta: 6.0.0-rc.10  latest: 6.8.0      mobx4: 4.15.7      

published 2 days ago by mweststrate <mweststrate@gmail.com>
```

But the latest release here in the repo is 6.7.0: https://github.com/mobxjs/mobx/releases
Looks like a tag for 6.8.0 is also missing.

@mweststrate is this omission on purpose? What changed in the new release?

**Comment by iChenLei** [comment] 2023-02-11 07:59
Hey, thanks for repoet, it's [Known issue](https://github.com/mobxjs/mobx/actions/runs/4135980389/jobs/7149185118 ).

**Comment by urugator** [comment] 2023-02-11 10:46
For the time being, changes are here:
https://github.com/mobxjs/mobx/pull/3601
Only mobx-react-lite failed to publish, unfortunately preventing creation of release notes.
Any help in investigating/fixing the issue is welcome.

**Comment by cmdcolin** [comment] 2023-03-26 21:12
I think it happened again with latest release here https://github.com/mobxjs/mobx/actions/runs/4518698760/jobs/7958739332

I translated the hex to ascii in the error message and it gave me something like this message

`npm WARN prepublish-on-install As of npm@5, `prepu...`

which leads to various threads like https://github.com/npm/npm/issues/16685

it may be worth changing prepublish->prepublishOnly, it would at least probably remove that "warning" and give a new error if not fix it

**Comment by mweststrate** [comment] 2023-07-12 18:29
Fixed in https://github.com/mobxjs/mobx/commit/278323ef234a42eb224a7716f89871e438c3e6cf

**Closed by mweststrate** 2023-07-12 18:29 UTC
Labels: 🐛 bug
