### ISSUE TITLE
`mobx-react-lite@4.0.2` observer not triggering component re-renders

### ISSUE THREAD

**Issue by johnsonsu** [mobxjs/mobx#3671] opened 2023-03-27 23:53 UTC
The `observer` of `mobx-react-lite` seems to not trigger the wrapped component to re-renders after upgrading from `mobx-react-lite@3.4.3` to `mobx-react-lite@4.0.2`.

**Intended outcome:**

When an `observable` value changes in the store, the `observer` component should re-render with the new value.

**Actual outcome:**

The `observer` component does not re-render when the `observable` value is updated.

**How to reproduce the issue:**

Code Sandbox: https://codesandbox.io/s/new-dawn-b2shxq?file=/src/App.js

Clicking "Push new element to data" button will push a new element to the `store.data` array using a store action.

However, the component does not re-render even thought `store.data` has been updated (see console logs).

If you change the `mobx-react-lite` version from `4.0.2` to `3.4.3` in the sandbox, the component will re-render when you click the "Push new element to data" button.

<img width="272" alt="Screenshot 2023-03-27 at 7 49 23 PM" src="https://user-images.githubusercontent.com/4886073/228091768-6aca121c-e7e0-4339-9715-5183dcc499c9.png">

**Versions**

`mobx-react-lite@4.0.2`

**Comment by imjordanxd** [comment] 2023-03-28 00:36
I've started using `observer` from `mobx-react` as a workaround

**Comment by kenbankspeng** [comment] 2023-03-28 00:48
@imjordanxd What version of mobx-react works for you? Because I think I'm seeing this same issue with mobx-react 8.0.0.

**Comment by kenbankspeng** [comment] 2023-03-28 00:58
The sandbox provided in the issue also fails using the observer from mobx-react 8.0.0 but works using mobx-react 7.6.0. No doubt same root cause as in mobx-react-lite@4.0.2.

**Comment by hheimerd** [comment] 2023-03-28 08:23
If you turn off StrictMode, then the update works.
I also found this bug on the 8th version of Mobx

**Comment by hheimerd** [comment] 2023-03-28 08:28
I noticed that the update is working with strict mode, but only in the Production build. Most likely the problem with compatibility with the DEV mode in React

Working configuration:
```
"mobx": "^6.7.0",
"mobx-react": "^7.6.0"
```

non -working configuration:
```
"mobx": "^6.7.0",
"mobx-react": "^8.0.0",
```

**Comment by urugator** [comment] 2023-03-28 13:38
I know the cause, but the fix seems to be non-trivial atm. The problem can also appear outside StrictMode (probably only when using concurrent features or when FinalizationRegistry isn't available), WIP PR https://github.com/mobxjs/mobx/pull/3673

**Comment by mweststrate** [comment] 2023-03-28 17:31
@urugator should we unpublish this major mobx-react / mobx-react-lite to avoid people taking it in production unawares until fixed?

**Comment by urugator** [comment] 2023-03-28 18:07
@mweststrate  Yea, probably. Atm I can provide a "fix", where everything basically works, bot not as intended - it won't use a global state version - however it's actually NOT using global version even now, because there was a pretty stupid typo:
https://github.com/mobxjs/mobx/pull/3673/files#diff-6b93715e19eb9119588dbe2af609a132062e61484d0d3de41b9e32e2d4a4ad5cL30-R30
And turned out switching to global version for some reason breaks interoperability with `mobx-react` or class components in general, dunno, have to investigate further, probably not sooner than over the weekend.

**Comment by evoyy** [comment] 2023-03-29 00:08
mobx-react v8.0.0 broke my apps. I wrap my app in `StrictMode` in development. If I remove `StrictMode`, it all works again. I already pushed another app to production but `StrictMode` is disabled in production so I dodged a bullet there.

**Comment by mweststrate** [comment] 2023-03-29 06:39
Yeah will unpublished when I'm behind a keyboard again

**Comment by LoveMeWithoutAll** [comment] 2023-04-26 07:33
Has this issue been resolved? I'm waiting so long.

**Comment by mweststrate** [comment] 2023-04-26 08:32
We reverted the 4.x release, we'll release it again, but needs some more
time. For now stick to 3.x

**Comment by mweststrate** [comment] 2023-07-12 18:07
Should be fixed by mobx-react@9. Thanks for the patience!

**Closed by mweststrate** 2023-07-12 18:07 UTC
Labels: 🐛 bug

**Comment by DeepakM02** [comment] 2023-08-07 09:19
is it fixed? @mweststrate  in `mobx-react-lite`?

**Comment by wuzinong** [comment] 2023-09-23 09:23
Is it fixed?

**Comment by ogaki-ori** [comment] 2024-06-20 09:07
is it fixed? @mweststrate in mobx-react-lite?

**Comment by kubk** [comment] 2024-06-20 09:24
@wuzinong Feel free to create a separate issue with a reproduction. No need to bump old issues
