### ISSUE TITLE
Computed properties and PropTypes

### ISSUE THREAD

**Issue by satispunk** [mobxjs/mobx#305] opened 2016-06-04 08:53 UTC
There are some weirdness. Please have a look at https://jsfiddle.net/8deztaj1/1/

If you have PropType for computed property it is computed 2 extra times

**Comment by Kukkimonsuta** [comment] 2016-06-06 13:01
This has nothing to do with prop types (also your propTypes are wrong, since you are passing down the store as `todoList` and not `unfinishedTodoCount`. The computed property is computed 3 times at start because:

```js
// snip

const store = new TodoList();

// first compute happens here, because you are accessing computed property
React.render(<TodoListView todoList={store} />, document.getElementById('mount'));

// second compute happens here, because you are mutating underlying data for computed property
store.todos.push(
    new Todo("Get Coffee"),
    new Todo("Write simpler code")
);

// third compute happens here for the same reason as previous
store.todos[0].finished = true;
```

To limit the number of recomputes while mutating data you can wrap your changes in a [transaction](http://mobxjs.github.io/mobx/refguide/transaction.html) or create an [action](http://mobxjs.github.io/mobx/refguide/action.html) that does that for you:

```js
transaction(() => {
  store.todos.push(
      new Todo("Get Coffee"),
      new Todo("Write simpler code")
  );
  store.todos[0].finished = true;
});
```

**Comment by satispunk** [comment] 2016-06-06 13:15
@Kukkimonsuta 

Alright, i was wrong with propTypes definition, here is the updated version https://jsfiddle.net/8deztaj1/2/

Your right about those 3 calls, but with propTypes defined there are 2 more calls (5 in total)

**Comment by mweststrate** [comment] 2016-06-14 11:54
I think this is a duplicate of https://github.com/mobxjs/mobx-react/issues/56. Will continue the discussion there.

**Closed by mweststrate** 2016-06-14 11:54 UTC
