### ISSUE TITLE
Computed members of observables don't show up in for...in or Object.keys

### ISSUE THREAD

**Issue by liron00** [mobxjs/mobx#347] opened 2016-06-20 00:03 UTC
```
> let o = observable({a: 5, b: {c: 6}, f: () => 9})
< Object {$mobx: ObservableObjectAdministration}

> o.a
< 5

> o.b
< Object {$mobx: ObservableObjectAdministration}

> o.f
< 9

> for (let x in o) {console.log(x)}
< a
< b
< undefined

> Object.keys(o)
< ["a", "b"]
```

**Comment by mweststrate** [comment] 2016-06-20 06:42
That is by design. Computed values are not enumerable so that objects are easier to generically copy past into other objects etc.

**Comment by liron00** [comment] 2016-06-20 11:54
Hm I don't think I get it, what's an example?

An argument for the semantics I expected is that now these two expressions are equivalent:

@observable a

1.
@computed get x() {
  return {a: this.a}
}

2.
x = {
  a: () => this.a
}

**Comment by mweststrate** [comment] 2016-06-20 14:10
@liron00 currently you can do something like:

```
class Todo {
   @observable done = false;
   @computed get isNotDone() {
       return !this.isDone;
   }

const t1 = new Todo();
const t2 = new Todo();
Object.assign(t1, t2);
```

The above works because `isNotDone` is non-enumerable and skipped. Otherwise it would try to copy `isNotDone` from `t2` to `t1`, which is rightfully rejected because computed values cannot be assigned to. Similarly this makes it easier to create a json representation etc, computed properties are not part of the state of an object, just like it's methods, and hence it is nice that they are not enumerable. Sometimes it would be nice if they were enumerable, but I think there are more scenerios where it is convenient that they are left out.

**Comment by liron00** [comment] 2016-06-20 14:27
Got it thanks. I agree your semantics are a better default for computed members of classes. Perhaps mine are preferable for plain objects but not a big deal.

**Comment by AriaFallah** [comment] 2016-06-20 16:25
@liron00 

You can use [Object.getOwnPropertyNames()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) to access the non enumerable props if you really want to get around it.

**Closed** 2016-06-21 09:44 UTC

**Comment by anatoliyarkhipov** [comment] 2017-03-29 05:22
Is there an easy way to make computed properties enumerable, at least for unit-test purposes? I'd like to use it with partial object matches, something like this:

```js
class State {
   @observable done = false;
   @computed get isNotDone() {
       return !this.done;
   }
}

// State.test.js

const state = new State

state.done = true

expect(state).toMatchObject({ isNotDone: false })
```

**Comment by ckwong90** [comment] 2018-08-01 09:05
I needed this for testing purposes too and also for implementing an auto recorder function wrapping all its observable props into autorun and pushing changes into an array.

I used 
```javascript
[..._getAdministration(node).values.keys()])
```

**Comment by JonDum** [comment] 2018-11-24 01:40
Yet another use case for allowing enumerable computeds:

I use a `@referenceTo(Model)` decorator (kinda similar to MST's identifier/reference)

```js
class User {
   @referenceTo(User) friends
}
```

Which makes a hidden empty instance of the model in a Symbol and instead returns that when trying to access the property (`friends` in this example). This allows me to then retrieve the details of the Model async and apply them to the instance and none of my components have to null check. Then when serializing it returns just the identifier instead of the whole model... except that's where it can't because `enumerable` is hard-coded as false:

https://github.com/mobxjs/mobx/blob/e099329e5d1246632b05601d79220295af3a03cb/src/types/observableobject.ts#L374-L388

It'd be great if we could keep the default the way it is now so there is no change for any `@computed` users, but if we **explicitly** add `enumerable: true` to a `computed()` call...

```js
const desc = computed(target, property, {
	enumerable: true, // the magic sauce
	get() {
		...
	},
	set(value) {
		...
	}
})
return desc
```
... just let it pass through here:

https://github.com/mobxjs/mobx/blob/master/src/api/computed.ts#L19-L39

The only workarounds I can think of are pretty gross — using some specific name and explicitly checking for that in a custom serializing function and adding it to the serialized object?
