### ISSUE TITLE
Ramda thinks mobx observable arrays are empty

### ISSUE THREAD

**Issue by andys8** [mobxjs/mobx#1490] opened 2018-04-09 09:15 UTC
I noticed there is an issue, when using mobx with other libraries. The concrete example is that [ramda](https://github.com/ramda/ramda) thinks observable arrays are empty. This is one example but I guess there are other, similar issues

Sample reproduction: https://stackblitz.com/edit/js-weoxpn

```js
const array0 = observable([]);
const array1 = observable([1, 2, 3]);

const isArrayEmpty0 = isEmpty(array0);
const isArrayEmpty1 = isEmpty(array1);
```
I'm aware of the [pitfalls section](https://mobx.js.org/best/pitfalls.html) and `.toJS()` as a solution. Because I use ramda a lot I'm thinking about the options we have to improve the behavior? Can there be changed something in mobx? Another solution would be to try to adapt ramda, but it would be hard to argument the change.

This is how ramda checks emptyness: https://github.com/ramda/ramda/blob/v0.25.0/source/empty.js

This is how ramda checks if something is an array: https://github.com/ramda/ramda/blob/v0.25.0/source/internal/_isArray.js#L16

`Object.prototype.toString.call(val)` will produce `[object Object]` with mobx, but ramda would want to see `[object Array]`. Because it's probably a bad idea to try to change the output, it is probably complicated to find a solution to fix this on the mobx side.

**Comment by mweststrate** [comment] 2018-04-09 09:29
As the pitfalls section indicates indeed, use `.slice()` (not the same as `toJS`, the latter is recursive) to pass an array to an external lib that doesn't support observables.

Once MobX 5 with proxy support has landed this is not strictly needed anymore, assuming your target JS engine supports proxies. 

Since this is documented and discussed extensively, closing the issue.

**Comment by andys8** [comment] 2018-04-09 09:35
Okay, thanks for the answer.

**Comment by urugator** [comment] 2018-04-09 09:40
I wonder whether implementing [`Symbol.toStringTag`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) would be enough? If that could provide (at least partial) interoperability with any lib which doesn't rely on `Array.isArray`, but rather on `Object.prototype.toString.call(obj)` (which seems quite common), I think it's worth considering...

**Comment by mweststrate** [comment] 2018-04-09 10:55
Ah, that could help in some cases indeed

>

**Comment by andys8** [comment] 2018-04-09 15:10
Sounds interesting. I was hoping for a proposed solution like this. 

@mweststrate Worth further investigation? Reopen the issue?

**Comment by mweststrate** [comment] 2018-04-09 15:12
Yes feel free to reopen for now. It won't fix the issue in general, but
occassionally it might help and it is non impactful, small change I think :)

Op ma 9 apr. 2018 om 17:10 schreef Andy <notifications@github.com>:

**Comment by andys8** [comment] 2018-04-09 15:15
Great. I think you have to reopen it.

**Comment by spion** [comment] 2018-04-09 16:29
With the isConcatSpreadable and toStringTag symbols, the problem is, they're not available in IE11, which is also currently the only serious browser that doesn't have proxies.

Does anyone know if modern polyfills patch array methods to make them respect isConcatSpreadable and toStringTag?

**Comment by andys8** [comment] 2018-04-09 17:09
The indicator on this site says there is a polyfill available for both of the mentioned methods.

https://cdn.polyfill.io/v2/docs/features/

**Comment by mweststrate** [comment] 2018-04-09 17:24
@spion good point. Forgot about that. Again.

@andys8 the problem is not that they are not polyfillable, but the problem is that the browser natively won't pick these up. Which means that using these features would make your app behave slightly different between engines that support these tags, and engines that don't. Which is against the design principles of MobX. (We prefer to have the same bug on all browsers, then having them on some, as the latter is much harder to debug & maintain). 

To clarify, `Symbol.toStringTag` itself can easily be polyfilled, but if `Object.prototype.toString` doesn't respect it, it doesn't help us further. And as far as I can see, the polyfills don't actively monkey-patch `Object.protoype.toString`

So, fixed in MobX 5 only it will be it seems...

**Comment by spion** [comment] 2018-04-09 18:13
@mweststrate no worries - when I said that, it did not occur to me to check if maybe `Object.prototype.toString` and `Array.prototype.concat` are polyfilled / patched to respect the symbols. 

Looks like in core.js (babel's polyfill) [toStringTag is implemented](https://github.com/zloirock/core-js#ecmascript-6-object) but isConcatSpreadable [isn't fully implemented](https://github.com/zloirock/core-js#missing-polyfills). Maybe we could add some documentation that for IE11 support those polyfills are required?

**Comment by urugator** [comment] 2018-04-10 14:25
[`@@isConcatSpreadable` and `@@species` is implemented in core-js@3 (currently alpha)](https://github.com/zloirock/core-js/pull/325)

**Closed** 2018-04-16 18:51 UTC

**Comment by mweststrate** [comment] 2018-04-16 19:10
Released `toStringTag` support for arrays in 4.2.0. This should solve your problem @andys8. Didn't implement `isConcatSpreadable`, can be done ones core-js is GA I think

**Comment by andys8** [comment] 2018-04-16 19:16
Wow, so great to hear this! Happy to see how the issue actually lead to an improvement in the end. Thanks for your efforts, @mweststrate.

**Comment by andys8** [comment] 2018-04-17 10:26
Giving it a try. Ramda's `type` recognizes observable object's now as Arrays. The change has lead to improvements. The example with `isEmpty` is now returning `false` for empty and non-empty arrays.

https://stackblitz.com/edit/js-qymnte

This is due to the implementation in Ramda. An empty instance is generated from the input and compared for equality with the input. The internal implementation of [`_equals`](https://github.com/ramda/ramda/blob/v0.25.0/source/internal/_equals.js) is not trivial. I think this is as far as it get's. Having quirks in one of those libraries to support the other is not a good solution. The cause is, that an observable array is not an array. I'm looking forward to mobx 5 and am curios what changes it will bring :)
