### ISSUE TITLE
Action.object in spy utility

### ISSUE THREAD

**Issue by rdrezner** [mobxjs/mobx#1887] opened 2019-01-30 17:09 UTC
Hi there.

I have a:

1. [x] Question: 

We are using MobX in our project. In one of our files we are using `spy` utility to track actions. Recently I upgraded from version 3 to 4 and came across an issue that I would like to ask you about. In MobX version 3 `action.object` in the `spy` utility for bound actions is keeping a reference to the object in which an action was defined. In MobX version 4 `action.object` seems to be keeping a reference to the object in which an action was called.

Is this an expected behavior or a bug? I couldn't find any information about it in the migration guidelines. Is it possible to get the reference to the object in which bound action was defined when using `spy` util in MobX 4? I need this to make my code working again. 

Here is the reproduction (click a checkbox and see the log in the console):
- MobX 3: https://jsfiddle.net/rdrezner/4Lo9swu6/2/ (action.object = TodoView)
- MobX 4: https://jsfiddle.net/rdrezner/9vL2xr6k/1/ (action.object = null)

Thanks in advance for your answers.

**Comment by mweststrate** [comment] 2019-02-06 08:46
Confirmed, looks like a regression bug indeed

**Comment by ItamarShDev** [comment] 2019-02-06 09:37
dibs :)

**Comment by ItamarShDev** [comment] 2019-02-06 21:12
@mweststrate seems that the issue lies here: https://github.com/mobxjs/mobx/blame/e5178f2fc3ab0a83048b71633601484922bd1c7b/src/core/action.ts#L19

**Comment by ItamarShDev** [comment] 2019-02-24 22:14
closing as the PR solving it merged to main branch.
@rdrezner thank you for submitting the issue!

**Closed by ItamarShDev** 2019-02-24 22:14 UTC
Labels: bug
