### ISSUE TITLE
installed mobx 6.6.2 but still got error mobx-react-lite@3 requires mobx at least version 6 to be available

### ISSUE THREAD

**Issue by felixliu226** [mobxjs/mobx#3572] opened 2022-11-13 15:53 UTC
**Intended outcome:**
I'm using React Native with MobX. When I initial the project (using Expo) and installed package mobx and mobx-react-lite, I got the error saying that "Error: mobx-react-lite@3 requires mobx at least version 6 to be available".

**Actual outcome:**
the package.json are 
`"dependencies": {
    "expo": "~47.0.3",
    "expo-status-bar": "~1.4.2",
    "mobx": "^6.6.2",
    "mobx-react-lite": "^3.4.0",
    "react": "18.1.0",
    "react-native": "0.70.5"
  },`

The mobx verison should be above version 6, but still got the error saying it need to be at least version 6.

**How to reproduce the issue:**
1. create an emtpy expo project `npx create-expo-app testing` and wait for the project initialized.
2. Install mobx and mobx-react-lite `npm install --save mobx mobx-react-lite`
3. build the project and run it `expo run:ios` and got the error 

ERROR  Error: mobx-react-lite@3 requires mobx at least version 6 to be available

**Versions**

"dependencies": {
        "expo": "~47.0.3",
        "expo-status-bar": "~1.4.2",
        "mobx": "^6.6.2",
        "mobx-react-lite": "^3.4.0",
        "react": "18.1.0",
        "react-native": "0.70.5"
      },

**Comment by mweststrate** [comment] 2023-07-12 18:25
Closing as I guess this one has expired in the mean time. But usually this is caused by having packages imported via different ways. Typically `yarn why mobx` (or the npm equivalent) shows how the packages end up in the dep tree.

**Closed by mweststrate** 2023-07-12 18:25 UTC
Labels: 🐛 bug
