### ISSUE TITLE
SyntaxError:  Using the export keyword between a decorator and a class is not allowed.

### ISSUE THREAD

**Issue by TheSixth** [mobxjs/mobx#1671] opened 2018-08-09 09:09 UTC
I have a Issue.SyntaxError:  Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead
`
@observer

export default class ShopCar extends Component {
...
}
`

**Comment by kuitos** [comment] 2018-08-09 09:32
check the babel plugin configuration

**Comment by mweststrate** [comment] 2018-08-10 07:51
Or just move the decorator as suggested. The final syntax is still under
debate at TC 39

Op do 9 aug. 2018 11:32 schreef Kuitos <notifications@github.com>:

**Comment by mweststrate** [comment] 2018-08-15 13:47
Duplicate of https://github.com/mobxjs/mobx-react/issues/528

**Closed by mweststrate** 2018-08-15 13:47 UTC
