### ISSUE TITLE
`isObservable(obj, property)` does not return true for unevaluated computed properties

### ISSUE THREAD

**Issue by jeffling** [mobxjs/mobx#373] opened 2016-06-29 04:58 UTC
```
@computed get computedVal() { returns some stuff }
constructor() {
  console.log(isObservable(this, 'computedVal')) // false
  console.log(this.computedVal);  // some stuff
  console.log(isObservable(this, 'computedVal')) // true
}
```

Workaround would be to evaluate your computed property before the check.

**Comment by mweststrate** [comment] 2016-06-29 06:08
Just double checking: you are transpiling using babel?

**Comment by jeffling** [comment] 2016-06-29 07:27
@mweststrate we're using typescript

**Comment by mweststrate** [comment] 2016-07-12 19:21
@jeffling I added a regression test, but the problem seems to be gone, I think it has been fixed with one of the late decorator fixes. Could you verify that?

**Closed** 2016-07-15 09:19 UTC
Labels: bug

**Comment by jeffling** [comment] 2016-08-19 20:19
Sorry for huge delay in response. Yes, confirmed fixe :)
