### ISSUE TITLE
@observable/@action + interface build error

### ISSUE THREAD

**Issue by rainmanhhh** [mobxjs/mobx#1808] opened 2018-11-13 09:32 UTC
what did I do:
1. create an empty react project with create-react-app --script-version=react-scripts-ts mobxtest and add deps: mobx & mobx-react
2. add a intf.ts in src dir:
```
export interface ITest { // if ITest is a class, build passed
  a?: string
}

export class A {  // if A is an interface, build passed
}
```
3. add a Store.ts in src dir:
```
import { action, observable } from 'mobx'
import { ITest } from './intf'

export class Store {
  @observable public t: ITest   // can't work with @observable
  @observable public testData: string = ''

  @action.bound
  public test(iTest: ITest) {  // can't work with @action.bound
    return this.testData = iTest.toString()
  }
  @action
  public test2 = (iTest: ITest) => {  // can't work with @action
    return this.testData = iTest.toString()
  }
}
export const store = new Store()
```
4. use store in App.tsx
```
import * as React from 'react';
import './App.css';

import { observer } from 'mobx-react'
import logo from './logo.svg';
import { store } from './store'

@observer
class App extends React.Component {
  public render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        {store.testData}  // use store
      </div>
    );
  }
}
export default App;
```
5. tsc compile success, but build with webpack report error:
`'./intf' does not contain an export named 'ITest'`

**interface from file contains classes can't work with @observable or @action**

**Comment by ItamarShDev** [comment] 2018-11-13 18:46
Your ITest in in `intf.ts`, not 'ITest.ts`
the problem is in the import

**Comment by rainmanhhh** [comment] 2018-11-14 02:20
> Your ITest in in `intf.ts`, not 'ITest.ts`
> the problem is in the import
> 
> [![Edit qx01xo1o94](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/qx01xo1o94)

changed filename to ITest.ts，still the same error

**Comment by mweststrate** [comment] 2018-11-30 15:40
@rainmanhhh I don't see any error in the codesandbox you've linked. Please provide a better reproduction

**Comment by rainmanhhh** [comment] 2018-12-07 01:19
> @rainmanhhh I don't see any error in the codesandbox you've linked. Please provide a better reproduction

don't run it directly, use webpack build

**Comment by mweststrate** [comment] 2019-03-14 10:14
closing as the question is probably not relevant anymore. Please provide a test repo directly next time, so that the time-to-reproduce is minimal.

**Closed by mweststrate** 2019-03-14 10:14 UTC
Labels: cannot reproduce
