### ISSUE TITLE
Suspense API support

### ISSUE THREAD

**Issue by nin-jin** [mobxjs/mobx#1646] opened 2018-07-21 07:53 UTC
I have a Idea:
  * [x] What problem would it solve for you?
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?

# API

- Calculation can be stopped by throwing `Promise` instance.
- After promise is `resolved` or `rejected` calculation should be restarted automatically.

# Profit

- Synchronous code without async/await everywhere.
- Intercommunication with other libraries.
- Automatic tracking of `waiting` state (when we can't render until data loaded, we should render placeholder).

# Changes

1. Catched promises shouldn't be logged as errors.
2. First computed, which have caught promise should subscribe on promise rejection and resolving and initiate actualization after.

# Other libraries with Suspense API support:

- [ReactJS](https://medium.com/@baphemot/understanding-react-suspense-1c73b4b0b1e6) (slave)
- [$mol_fiber](https://github.com/eigenmethod/mol/tree/master/fiber) (master/slave)

**Comment by nin-jin** [comment] 2018-07-22 06:47
```
class User {
    firstName: string
    lastName: string
}
```

```
function lazy< Entity >( entity : Entity , fetch: ( field : PropertyKey )=> Promise<any> ) {
    return new Proxy( new Entity , {
        get : ( entity , field )=> {
            if( entity[ field ] === undefined ) throw fetch( field )
            return entity[ field ]
        } ,
    } )
}
```

```
const user = new User
const lazyUser = lazy( user , async ( field )=> {
    const json = await ( await fetch( '/user' ) ).json()
    Object.assign( user , json.data.user )
} )
```

```
function UserName( user : User ) {
    return <div>{ user.firstName } { user.lastName }</div>
}
```

function PageTitle( config : Config , user : User , page : Page ) {
    return <title>{ config.showName && `[${ user.firstName  } ${ user.lastName }] ` } { page.title }</title>
}

**Comment by nin-jin** [comment] 2018-07-22 09:34
Simple example (with mobx usage in master) in this test: https://github.com/mobxjs/mobx/pull/1647/commits/1220eee8b74ccc1552fd55af1fc8c4d09a9606c0#diff-19c935498f7daabdc3c5f9a02361e212
But this issue is about masters without mobx like example below.

**Comment by mayorovp** [comment] 2018-07-23 12:47
This behavior can be achieved by current mobx easily:

```js
function lazy< Entity >( entity : Entity , fetch: ( field : PropertyKey )=> Promise<any> ) {
    return new Proxy( entity , {
        get : ( entity , field )=> {
            if( entity[ field ] === undefined ) {
                const atom = mobx.createAtom(field.toString());
                atom.reportObserved();

                const promise = throw fetch( field );
                promise.then(() => atom.reportChanged(), () => atom.reportChanged());
                throw promise;
            }
            return entity[ field ]
        } ,
    } )
}
```

**Comment by mayorovp** [comment] 2018-07-23 13:07
Another way:

```typescript
function lazy< Entity >( entity : Entity , fetch: ( field : PropertyKey )=> Promise<any> ) {
    return new Proxy( entity , {
        get : ( entity , field )=> {
            if( entity[ field ] === undefined && !mobx.isObservableProp(entity, field)) {
                mobx.extendObservable(entity, { [field]: undefined });
                mobx.get(entity, field);
                throw fetch( field );
            }
            return entity[ field ]
        } ,
    } )
}
```

**Comment by nin-jin** [comment] 2018-07-23 19:49
@mayorovp, your examples like my second example requires mobx in master. Think about crosslibrary communications. Currently, we can't use `futureFetcher`, `$mol_fiber` and other inside MobX.

**Comment by mayorovp** [comment] 2018-08-02 12:36
@nin-jin No problem:

```javascript
function catchSuspense<T>(fn: () => T) {
    try { return fn(); }
    catch (error) {
        if (error instanceof Promise) {
            const atom = mobx.createAtom("suspense");
            atom.reportObserved();
            error.then(() => atom.reportChanged(), () => atom.reportChanged());
        }
        throw;
    }
}
```

**Comment by nin-jin** [comment] 2018-08-02 16:47
@mayorovp I don't like to remember about manually wrapping of every call to additional wrapper. There is SuspenseAPI, which supported by other libraries. I think MobX should support it natively. `$mol_atom2` will support it too.

**Comment by zerkalica** [comment] 2018-08-09 12:08
@mayorovp 

catchSuspense adds suspense magic for whole component computations, not for each used computable value.

catch section in catchSuspense never calls, if fn contains custom error/loading handler without rethrow:

```js
function MyComponent(props) {
  return catchSuspense(() => {
    try {
       return <div>{props.user.name}</div>
    } catch(error) {
        // Custom error/loading handling
    }
  })
}
```

Better to handle promise inside atom, when accessing props.user.name.

@mweststrate 

Mobx is about reactivity, but reactivity tightly coupled with asyncrony. What if extends base mobx idea to asynchrony and produce pseudo-synchronous code. React tries to do this via [suspense api](https://github.com/sw-yx/fresh-async-react) and promises and it's a good idea.

Currently, mobx/computed not compatible (not transparent) with react suspense api.

Above example produce "An update was suspended for longer than the timeout, but no fallback UI was provided." Without ``` @computed ``` decorator suspense works fine.

```js
class DogRepository {
  random() {
    if (this._cachedDog) return this._cachedDog;
    throw fetch("https://dog.ceo/api/breeds/image/random")
      .then(res => res.json())
      .then(data => {
        this._cachedDog = data.message;
      });
  }
}

class RawSuspense extends React.Component {
  render() {
    return <img src={this.props.dogs.random()} />;
  }
}

class MobxStore {
  @observable count = 0;
  constructor(dogs) { this.dogs = dogs; }
  // Remove @computed to show suspense api in action
  @computed get some() {
    return {
      count: this.count,
      dog: this.dogs.random()
    };
  }

  @action.bound add() { this.count++; }
}

@observer class App extends React.Component {
  render() {
    const { store } = this.props;
    return (
      <div>
        <button onClick={store.add}>Add</button>: {store.count}
        <br />
        <img src={store.some.dog} />
      </div>
    );
  }
}

const store = new MobxStore(new DogRepository());
```
[sandbox](https://codesandbox.io/s/y063v8qpjj)

Pseudo-synchronous code is less boilerplate (no streams, no any visible data wrappers). Some example from my [lom_atom todomvc](https://github.com/zerkalica/rdi-examples/blob/master/src/examples/todomvc/models/TodoRepository.js#L28)

```js
export default class TodoRepository {
    @mem get todos(): Todo[] {
        return this._fetcher.get('/todos').json()
            .map((data: ITodoData) => new Todo(data, this))
    }
    set todos(todos: Todo[]) {}
```

**Comment by zerkalica** [comment] 2018-08-09 13:41
@mayorovp You right. But problem in non-trasparent computed behaviour with throw. Looks like computed caches exception.

**Comment by mayorovp** [comment] 2018-08-09 13:47
@zerkalica of course it is! See https://mobx.js.org/refguide/computed-decorator.html#note-on-error-handling

Why you called this behavior "non-transparent"?

**Comment by zerkalica** [comment] 2018-08-09 15:03
@mayorovp Not this, computable itself works like in documentation. But not in observer or autorun, look at my example above.

Or this example without mobx-react, where i simulate react behaviour: 
```js
function render() {
  try {
    document.body.innerHTML = JSON.stringify(store.some);
  } catch (e) {
    if (e instanceof Promise) {
      if (cnt < 30) {
        e.then(render);
        document.body.innerHTML = "Loading...";
      } else {
        document.body.innerHTML = "Overflow";
      }
      cnt++;
    } else {
      throw e;
    }
  }
}

// Without autorun suspense works
autorun(() => {
  render();
});
```
[raw-mobx-computable-recalculate sandbox](https://codesandbox.io/s/1wq3n0w3k7)

**Comment by mweststrate** [comment] 2018-08-17 14:44
@zerkalica @nin-jin I am not sure whether I understand this thread correctly, but suspens + promises in from computes seems to work fine for me ...

https://codesandbox.io/s/kmzyyw36xo

**Comment by mweststrate** [comment] 2018-08-17 14:55
The only thing I don't get is that the dog counter is not updated properly, which does work if the dogs themselves are not rendered.

**Comment by zerkalica** [comment] 2018-08-17 15:35
@mweststrate It works properly, only if observable mobx cache used ``` @observable dog ```. Remove ``` @observable ``` and got an infinite loop, computed caches Promise exception.

Dog may be in separate library and doesn't know about mobx but knows about library-independed suspense paradigm. It's not a bug, but not compatible with suspense behavour.

In react 16.4.2, used in you example, suspens disabled by default: see [var enableSuspense = false;](https://unpkg.com/react@16.4.2/umd/react.development.js).

Use [react-suspense-starter](https://github.com/palmerhq/react-suspense-starter) or 16.4.0-alpha.0911da3 version from my examples.

**Comment by mweststrate** [comment] 2018-08-17 16:10
Behavior changes with different versions of suspense https://codesandbox.io/s/61yvp6lmj3

@zerkalica you might not have been using the latest version of that link (I reverted the build numbers), for me https://codesandbox.io/s/kmzyyw36xo works the same with or without `@computed`. Yes you have to throw the same promise every time, but that is the whole model of suspense, and not related to MobX, but to suspense.

**Comment by zerkalica** [comment] 2018-08-17 16:52
@mweststrate What is whole model of suspense? Promise-based suspense does not limit as about cache realization. How to communicate with other libraries, with any cache realization?

Look at facebook [simple-cache-provider](https://github.com/facebook/react/blob/master/packages/simple-cache-provider/src/SimpleCacheProvider.js#L293), which used in Dan's suspense demo. It's cache not observable, how to use it with mobx?

Suspense can be used everywhere. It's a raw, but more common paradigm than mobx. Like threads or [fibers](https://gist.github.com/nin-jin/5408ef8f16f43f1b4fe9cbcea577aac6).

**Comment by mweststrate** [comment] 2018-08-17 18:30
I think I interpreted your previous comment wrong. Anyway at this point I don't see any problem in combining MobX and suspense nor any reason to change anything. So I think this issue can be closed until the is a clear example of what goes wrong.

But since suspense is not documented nor deeply understood yet,  reasoning about the correct behavior is probably still highly speculative at this point

**Comment by zerkalica** [comment] 2018-08-17 18:54
[This example](https://codesandbox.io/s/1wq3n0w3k7) not clear?

**Comment by spion** [comment] 2018-08-17 20:46
The model of mobx computed values has always been clear: computeds are "pure functions", or at least functions idempotent to their arguments, where the arguments are the dependent observables. Any operations that are impure in this sense are not guaranteed to behave in any particular way

In this case, a non-pure (in the mobx model sense) function is invoked from a computed, and without the special behavior of suspense, its result simply wouldn't ever update.

IMO the exception model of suspense is really one giant hack. Any library between the promise thrower and react may intercept exceptions and decide to handle them, somehow. Relying on intermediate libraries not doing that puts improper coupling, where every library has to deal with this special-cased react behavior and ensure not to touch those thrown promises. So, every single library between the thrower and react is coupled with the suspense throw API, which is crap.

**Comment by mweststrate** [comment] 2018-08-18 14:59
Closing this issue for now; React suspense works fine as it seems for now. Custom reactions with alternative schedulers can be build based of the [`Reaction`](https://github.com/mobxjs/mobx/blob/master/src/core/reaction.ts) and can be as far as I see now be build in user land code, where the `try / catch` can be internalized in the function that needs to be `track`ed

**Closed by mweststrate** 2018-08-18 14:59 UTC

**Comment by nin-jin** [comment] 2018-08-23 08:16
It's OK if you don't want to make your lib more interoperable :-) But try to use SuspenseAPI in some of your project. It's very cool.
