### ISSUE TITLE
array.filter don't update the data

### ISSUE THREAD

**Issue by stephane-r** [mobxjs/mobx#1315] opened 2018-01-22 14:29 UTC
Hi community :)

I would like create a array observable with filter.

My exemple :

`@observable list = [];`

And i've some method with filter :

```
  @action findUserPresentations(userId) {
    return this.list.filter(item => userId === item.userId);
  }
```

With `findUserPresentations`, if i update `list` array, no data will change. If i edit my method and i add just `return this.list.slice()`, it work.

You can see my container :

```
@observer
@inject('user', 'presentations')
class MyPresentationsContainer extends React.Component {

  get presentations() {
    return this.props.presentations.findUserPresentations(this.props.user.id);
  }

  render() {
    return (
      <MyPresentations
        presentations={this.presentations}
      />
    );
  }
}
```

My problem is with `.filter`, because i think it return an new array ^^

Do you know how i can have an observable array filtered ?

Thank you community :)

**Comment by mweststrate** [comment] 2018-01-22 14:48
.filter returns an array indeed, doesn't update the current one. If you
want to update the list with the filtered ones, use
`this.list.replace(this.list.filter(predicate))` (`replace` is shorthand
for `ar.splice(0, ar.length, ...newItems)`)

Op ma 22 jan. 2018 om 15:29 schreef Stéphane <notifications@github.com>:

**Comment by stephane-r** [comment] 2018-01-22 16:18
Hi @mweststrate 

Thank for your response.

I've try this code, but same result : `return this.list.replace(this.list.filter(item => userId === item.userId));`

**Comment by mweststrate** [comment] 2018-01-22 16:20
Best provide a little more context then. "No data will change"  is quite a
vague statement

Op ma 22 jan. 2018 om 17:18 schreef Stéphane <notifications@github.com>:

**Comment by mweststrate** [comment] 2018-01-22 16:22
Btw, are you sure you shouldn't be creating a _computed_ instead of an
_action_ (in which case you original filter is correct)? Is your intention
to throw away all items not belonging to the user, or just filtering away
all items not belonging to the user?

Op ma 22 jan. 2018 om 17:20 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by stephane-r** [comment] 2018-01-22 16:32
Yep, it's `action` type :

```
  @action findUserPresentations(userId) {
    return this.list.filter(item => userId === item.userId);
  }
```
I would like just filtering away all items not belonging to the user :)

**Comment by stephane-r** [comment] 2018-01-23 09:05
No idea for show an `array.filter` by `value` ?

**Comment by mweststrate** [comment] 2018-01-23 09:21
Can you describe your problem in more detail? I think you are confusing computed and action. Action is intended to make changes to the state, however, your action isn't modifying state, but deriving information from it. Which is normally the job of computed values. (as a rule of thumb, actions usually don't `return` anything)

But your questions does not have enough context to say something useful. Comments like "he returns the same but 2x" or "No data will change" are meaningless to anybody who isn't looking over your shoulder. So please clarify your problem first. Ideally fork one of the fiddles linked in the readme or the issue template so that people in here so that we can see what you mean.

**Comment by mweststrate** [comment] 2018-01-23 14:40
Closing here as the question is also on SO: https://stackoverflow.com/questions/48379574/mobx-dont-update-observable-array/48380609?noredirect=1#comment83781452_48380609

But the problem is that your are using `findUserPresentations` as a derivation, but declaring it as an action. Dropping `@action` should fix the issue.

**Closed by mweststrate** 2018-01-23 14:40 UTC
