### ISSUE TITLE
Problem with passing observable objects down to other components

### ISSUE THREAD

**Issue by shpyo** [mobxjs/mobx#1509] opened 2018-04-20 09:51 UTC
Hey.
I have a two independent components which have their own MobX state (`ComponentA` and `ComponentB`).
I have problem with passing observable objects from one component to other.
In `ComponentA` I include `ComponentB`.

This is how it looks in `ComponentA`
```js
import ComponentB from '@myDomain/ComponentB';

class Component extends React.Component {
	// ...

	carDetails = (e) => {
		// getCarDetails is an @action method
		// it makes an ajax call and updates `carDetails`
		carState.getCarDetails(e.target.value);
	}

	render() {
		// both variables are @observable
		const { carDetails, carToken } = carState;

		return (
			<Provider carState={carState}>
				<div className="details">
					<h2>Details: {carDetails.name}</h2>
					<select onChange={this.changeCar}>
					</select>
					<ComponentB
						carDetails={carDetails}
					/>
				</div>
			</Provider>
		);
	}
}
```

And now, when I update `carDetails` (an `@observable` prop in `ComponentB`'s MobX state) `ComponentB` is re-rendered but `carDetails` wasn't updated in `ComponentB` (has it's initial values).

Am I missing something?
However when do something like this:
```js
<ComponentB
	carDetails={toJS(carDetails)}
/>
```
Works fine every time.

**Comment by urugator** [comment] 2018-04-20 10:16
`ComponentB` must be `@observer` as well
Check: https://mobx.js.org/best/react.html
and perhaps: https://github.com/mobxjs/mobx/issues/1142

**Comment by shpyo** [comment] 2018-04-20 11:16
I just noticed that it works without `toJS` after second time (I have to change car twice to see changed state).
@urugator thanks for your answer. Checking...

**Comment by shpyo** [comment] 2018-04-20 14:10
@urugator I have checked my code. `ComponentB` is already an `@observer`

**Comment by urugator** [comment] 2018-04-20 14:25
I read the description wrong, I thought that component isn't updating...
I don't understand what the problem is ... `carDetails` in your sample is a function, why would you call `toJS` on a function? Post the whole code or ideally set up a reproduction on codesandbox if you can...

**Comment by mweststrate** [comment] 2018-05-03 14:10
Closing for the lack of a good reproduction. The above example is confusing as there seem to be multiple definitions of `carDetails`... 

Feel free to reopen when a reproduction is provided.

**Closed by mweststrate** 2018-05-03 14:10 UTC
