### ISSUE TITLE
maximum call stack size exceeded is ocurring again

### ISSUE THREAD

**Issue by sakopqiu** [mobxjs/mobx#1812] opened 2018-11-15 03:08 UTC
I have an  Issue:
I have read several threads talking about `maximum call stack size exceeded`  before, but It seems that this problem occurs again in the 5.5.2 and even the latest 5.6.0 version.

Here is a very simple code snippet which reproduces that bug.
```
@observer
export default class Test extends React.Component {
  @observable
  a = 1;

  @observable
  b = 2;

  @computed // if you remove this annotation, everything will be fine
  get c() {
    return this.a + this.b;
  }

  render() {
    return (
      <div>
        {this.a} plus {this.b} equals {this.c}
      </div>
    );
  }
}
```

**Comment by mweststrate** [comment] 2018-11-16 16:21
@sakopqiu can you include a minimal reproduction / share your babel configuration?

**Comment by lijunle** [comment] 2018-11-20 09:36
Hit the same issue with `@computed` decorator with version 5.6.

**Comment by mweststrate** [comment] 2018-11-20 10:12
Since this is primarily a setup problem (only happens under certain build
setups), please provide a minimal reproducible project repository

Op di 20 nov. 2018 om 10:36 schreef Junle Li <notifications@github.com>:

**Comment by mweststrate** [comment] 2018-11-30 16:00
Closing, again, for the lack of a reproduction. It isn't happening for everyone. So further reports have no use without reproduction.

**Closed by mweststrate** 2018-11-30 16:00 UTC
Labels: cannot reproduce

**Comment by lijunle** [comment] 2018-12-03 16:53
It is environment dependent. I have an expo project. For the same code, iOS is running fine but Android is throwing exception. It may be related to Android JSCode runtime.
