### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PengQingYao** [mobxjs/mobx#3403] opened 2022-05-19 05:43 UTC
![image](https://user-images.githubusercontent.com/40662148/169217964-50d34570-e057-45d3-b344-6269efbe2aa3.png)
![image](https://user-images.githubusercontent.com/40662148/169218038-1f82c306-4666-4f84-ba80-f3c2dfde7a30.png)

`this.menus`  is observable，The menu is the data returned from the server， but the amount of data is very large，the data size is 6M and data structure is a tree。 
 exclude code 'this.menus = menus'，throw error 'Maximum call stack size exceeded';

**Comment by PengQingYao** [comment] 2022-05-19 05:47
The method 'buildTrees' is  to turn list into tree without any error。

**Comment by mweststrate** [comment] 2022-05-19 15:36
do you need the tree to be fully observable objects, or just the reference to the tree? How deep is the tree?

**Comment by Asweallcan** [comment] 2022-05-25 09:43
I have the same problem with same error, just push item to array

**Comment by mweststrate** [comment] 2022-05-25 10:52
This issue has no reproduction and lacks further context, so please either update or close the issue.

**Comment by Asweallcan** [comment] 2022-05-25 14:05
I have no problem, i think there is circular reference.

**Comment by mareksuscak** [comment] 2022-06-30 22:36
Same problem after upgrading to `mobx-react` to `7.5.1` from `7.5.0` and mobx from `6.6.0` to mobx `6.6.1`. This is a Next.js app with static rendering on and it only breaks on the server it seems, not the client.

**Comment by lucasengel** [comment] 2022-07-04 19:20
Since `7.5.1` we're also facing the same problem. Trying to narrow down what might be causing this.

**Comment by kubk** [comment] 2022-07-05 11:30
Hi @lucasengel 
Is there a chance to create a small reproducible codesandbox here? https://codesandbox.io/s/minimal-mobx-react-project-ppgml?file=/index.js

**Comment by lucasengel** [comment] 2022-07-06 15:16
@kubk I'll try to narrow down the issue. I'm assuming it's something to do with the stores initialization. Might take a bit for me to get back.

**Comment by mweststrate** [comment] 2022-07-06 15:19
@mareksuscak  / @lucasengel  I think your issue is a duplicate of #3448. The stacktrace is entirely different (recursion during rendering) than the one reported in this issue, which is a recursion during observable creation (either due to being too deep, or due to being a cyclic data structure)

**Comment by lucasengel** [comment] 2022-07-14 19:03
That actually fixed the issue we were experiencing here. Thanks!

**Closed** 2022-07-18 09:59 UTC
Labels: 💬 discuss, ♺ needs-reproduction
