### ISSUE TITLE
Uncaught TypeError: i is not a function when I upgraded React, Mobx and Mobx-React

### ISSUE THREAD

**Issue by coreyarch1234** [mobxjs/mobx#1871] opened 2019-01-18 20:12 UTC
I have an issue when running my app. I get the error ```Uncaught TypeError: i is not a function``` on the client. I recently upgraded to react 16.7. I upgraded mobx to 5.6.0 and mobx-react to 5.4.3. 

This is my devDependencies:
```"devDependencies": {
    "autoprefixer": "6.3.7",
    "axios": "0.13.1",
    "babel-cli": "^6.18.0",
    "babel-code-frame": "6.11.0",
    "babel-core": "^6.18.2",
    "babel-eslint": "^7.1.0",
    "babel-generator": "6.11.4",
    "babel-helper-bindify-decorators": "6.8.0",
    "babel-helper-builder-binary-assignment-operator-visitor": "6.8.0",
    "babel-helper-builder-react-jsx": "6.9.0",
    "babel-helper-call-delegate": "6.8.0",
    "babel-helper-define-map": "6.9.0",
    "babel-helper-explode-assignable-expression": "6.8.0",
    "babel-helper-explode-class": "6.8.0",
    "babel-helper-function-name": "6.8.0",
    "babel-helper-get-function-arity": "6.8.0",
    "babel-helper-hoist-variables": "6.8.0",
    "babel-helper-optimise-call-expression": "6.8.0",
    "babel-helper-regex": "6.9.0",
    "babel-helper-remap-async-to-generator": "6.11.2",
    "babel-helper-replace-supers": "6.8.0",
    "babel-helpers": "6.8.0",
    "babel-jest": "^16.0.0",
    "babel-loader": "^6.2.8",
    "babel-messages": "6.8.0",
    "babel-plugin-check-es2015-constants": "6.8.0",
    "babel-plugin-lodash": "3.2.9",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-syntax-async-functions": "6.8.0",
    "babel-plugin-syntax-class-constructor-call": "6.8.0",
    "babel-plugin-syntax-class-properties": "6.8.0",
    "babel-plugin-syntax-decorators": "6.8.0",
    "babel-plugin-syntax-do-expressions": "6.8.0",
    "babel-plugin-syntax-exponentiation-operator": "6.8.0",
    "babel-plugin-syntax-export-extensions": "6.8.0",
    "babel-plugin-syntax-flow": "6.8.0",
    "babel-plugin-syntax-function-bind": "6.8.0",
    "babel-plugin-syntax-jsx": "6.8.0",
    "babel-plugin-syntax-object-rest-spread": "6.8.0",
    "babel-plugin-syntax-trailing-function-commas": "6.8.0",
    "babel-plugin-transform-async-to-generator": "6.8.0",
    "babel-plugin-transform-class-constructor-call": "6.8.0",
    "babel-plugin-transform-class-properties": "6.11.5",
    "babel-plugin-transform-decorators": "6.8.0",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-do-expressions": "6.8.0",
    "babel-plugin-transform-es2015-arrow-functions": "6.8.0",
    "babel-plugin-transform-es2015-block-scoped-functions": "6.8.0",
    "babel-plugin-transform-es2015-block-scoping": "6.10.1",
    "babel-plugin-transform-es2015-classes": "6.9.0",
    "babel-plugin-transform-es2015-computed-properties": "6.8.0",
    "babel-plugin-transform-es2015-destructuring": "6.9.0",
    "babel-plugin-transform-es2015-duplicate-keys": "6.8.0",
    "babel-plugin-transform-es2015-for-of": "6.8.0",
    "babel-plugin-transform-es2015-function-name": "6.9.0",
    "babel-plugin-transform-es2015-literals": "6.8.0",
    "babel-plugin-transform-es2015-modules-commonjs": "6.11.5",
    "babel-plugin-transform-es2015-object-super": "6.8.0",
    "babel-plugin-transform-es2015-parameters": "6.11.4",
    "babel-plugin-transform-es2015-shorthand-properties": "6.8.0",
    "babel-plugin-transform-es2015-spread": "6.8.0",
    "babel-plugin-transform-es2015-sticky-regex": "6.8.0",
    "babel-plugin-transform-es2015-template-literals": "6.8.0",
    "babel-plugin-transform-es2015-typeof-symbol": "6.8.0",
    "babel-plugin-transform-es2015-unicode-regex": "6.11.0",
    "babel-plugin-transform-exponentiation-operator": "6.8.0",
    "babel-plugin-transform-export-extensions": "6.8.0",
    "babel-plugin-transform-flow-strip-types": "6.8.0",
    "babel-plugin-transform-function-bind": "6.8.0",
    "babel-plugin-transform-object-assign": "6.8.0",
    "babel-plugin-transform-object-rest-spread": "6.8.0",
    "babel-plugin-transform-react-display-name": "6.8.0",
    "babel-plugin-transform-react-jsx": "6.8.0",
    "babel-plugin-transform-react-jsx-source": "6.9.0",
    "babel-plugin-transform-regenerator": "6.11.4",
    "babel-plugin-transform-strict-mode": "6.11.3",
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-react-native": "1.9.0",
    "babel-preset-stage-0": "6.5.0",
    "babel-preset-stage-1": "6.5.0",
    "babel-preset-stage-2": "6.11.0",
    "babel-preset-stage-3": "6.11.0",
    "babel-register": "6.11.6",
    "babel-runtime": "6.11.6",
    "babel-template": "6.9.0",
    "babel-traverse": "6.12.0",
    "babel-types": "6.11.1",
    "better-console": "0.2.4",
    "classnames": "2.2.5",
    "cross-env": "^3.1.3",
    "del": "2.2.1",
    "del-cli": "0.2.0",
    "elemental": "0.5.14",
    "eslint": "^3.9.1",
    "eslint-config-way2b1": "git://github.com/miketoth/eslint-config-way2b1.git",
    "eslint-plugin-react": "5.1.1",
    "express": "4.13.4",
    "extend": "3.0.0",
    "extract-text-webpack-plugin": "1.0.1",
    "gulp": "3.9.1",
    "gulp-concat-css": "2.3.0",
    "gulp-dedupe": "0.0.2",
    "gulp-help": "1.6.1",
    "gulp-json-editor": "2.2.1",
    "gulp-minify-css": "1.2.4",
    "gulp-plumber": "1.1.0",
    "gulp-print": "2.0.1",
    "gulp-rename": "1.2.2",
    "gulp-rtlcss": "1.0.0",
    "history": "3.0.0",
    "html-webpack-plugin": "2.19.0",
    "jest": "22.3.0",
    "lodash": "^4.17.4",
    "map-stream": "0.1.0",
    "mkdirp": "0.5.1",
    "mobx": "5.6.0",
    "mobx-autorun-async-immediate": "^1.2.0",
    "mobx-react": "5.4.3",
    "mocha": "^3.1.2",
    "moment": "2.14.1",
    "morgan": "1.7.0",
    "nodemon": "1.9.2",
    "nsp": "^2.8.0",
    "react": "16.7",
    "react-autosize-textarea": "0.3.2",
    "react-dom": "16.7",
    "react-dropzone": "3.5.3",
    "react-flex-slick": "0.5.0",
    "react-hot-loader": "3.0.0-beta.2",
    "react-infinite": "^0.10.0",
    "react-infinite-calendar": "1.1.17",
    "react-motion": "0.4.4",
    "react-notification-system": "0.2.7",
    "react-responsive": "1.1.5",
    "react-router": "^3.0.0",
    "react-select": "1.0.0-rc.2",
    "react-select-search": "0.5.3",
    "react-tag-input": "4.0.1",
    "react-textarea-autosize": "4.0.5",
    "react-tooltip": "3.1.5",
    "react-transform-catch-errors": "1.0.2",
    "react-window-resize-listener": "1.0.0",
    "run-sequence": "1.2.2",
    "selection-range": "1.1.0",
    "semantic-ui": "2.2.10",
    "semantic-ui-css": "2.2.4",
    "stardust": "0.29.0",
    "uglify-js": "2.7.0",
    "victory": "0.12.1",
    "victory-chart": "12.0.1",
    "webpack": "1.13.1",
    "webpack-dev-server": "1.14.1",
    "webpack-md5-hash": "0.0.5",
    "winston": "2.2.0",
    "yamljs": "0.2.8"
  },
```

This is my stacktrace:
```
Uncaught TypeError: i is not a function
    at Object.<anonymous> (vendor.e0cb6bebdf62c051712c.js:formatted:17773)
    at Object.<anonymous> (vendor.e0cb6bebdf62c051712c.js:formatted:28)
    at t (vendor.e0cb6bebdf62c051712c.js:formatted:10)
    at Object.<anonymous> (main.7cd1d55a5f85d6985997.js:24)
    at t (vendor.e0cb6bebdf62c051712c.js:formatted:10)
    at Object.<anonymous> (main.7cd1d55a5f85d6985997.js:24)
    at t (vendor.e0cb6bebdf62c051712c.js:formatted:10)
    at Object.<anonymous> (main.7cd1d55a5f85d6985997.js:24)
    at t (vendor.e0cb6bebdf62c051712c.js:formatted:10)
    at Object.<anonymous> (main.7cd1d55a5f85d6985997.js:23)
VM19:1 WebExtension::executeScript: content script injected
```

When I check where the function i is called, this is what I see:

```
function(e, t, n, r) {
    "use strict";
    var o = n(510)
      , i = n(r);
    if ("undefined" == typeof o)
        throw Error("create-react-class could not find the React object. If you are using script tags, make sure that React is being loaded before create-react-class.");
    var u = (new o.Component).updater;
    e.exports = i(o.Component, o.isValidElement, u)
}
```

I cannot seem to run the project because of this. I would appreciate any help in figuring out why that is the case. Please let me know if you need any more clarification.

**Comment by mweststrate** [comment] 2019-01-18 20:55
Please provide a reproduction. Any reason why you suspect mobx or
mobx-react to be the cause?

Op vr 18 jan. 2019 om 21:12 schreef Corey Harrilal <notifications@github.com

**Comment by mweststrate** [comment] 2019-02-06 09:03
Closing for the lack of any further info

**Closed by mweststrate** 2019-02-06 09:03 UTC
