### ISSUE TITLE
[5.10.1] Extending Array.prototype – `Cannot read property 'value' of undefined` 

### ISSUE THREAD

**Issue by idudinov** [mobxjs/mobx#2021] opened 2019-06-24 11:47 UTC
Hi there!

[TL;DR: code sample](https://codesandbox.io/s/mobx-crash-arrayprototype-5101-z43ux)

I have a:
 - [x] Issue:
  * [x] **Provide error messages including stacktrace**
```
mobx.module.js:2199 Uncaught TypeError: Cannot read property 'value' of undefined
    at extendObservableObjectWithProperties (mobx.module.js:2199)
    at Function.object (mobx.module.js:542)
    at ObservableValue.deepEnhancer [as enhancer] (mobx.module.js:378)
    at ObservableValue../node_modules/mobx/lib/mobx.module.js.ObservableValue.prepareNewValue (mobx.module.js:747)
    at ObservableObjectAdministration../node_modules/mobx/lib/mobx.module.js.ObservableObjectAdministration.write (mobx.module.js:3871)
    at Test.set [as data] (mobx.module.js:4094)
    at Module../src/test.tsx (test.tsx:34)
    at __webpack_require__ (bootstrap:19)
    at Module../src/index.tsx (index.tsx:4)
    at __webpack_require__ (bootstrap:19)
```
  * [x] Provide a **minimal** sample reproduction.
[Extending Array.prototype – MobX 5.10.1](https://codesandbox.io/s/mobx-crash-arrayprototype-5101-z43ux) 
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
Seems like this issue relates to extending `Array.prototype`. Having such extension is not a must in most project, and even might be not safe, but with Typescript (which I use) I think such a case would be common.

  * [x] State the versions of MobX and relevant libraries.
Crashes on `5.10.1`, doesn't crash on `5.9.4`.

Thanks!

**Comment by FredyC** [comment] 2019-06-24 12:44
> * but with Typescript (which I use) I think such a case would be common.

Uh, can you elaborate on how TypeScript makes it more common? :) On the contrary, it could be rather annoying to correctly modify something like that.

@xaviergonz Any chance this broken behavior might be related to your https://github.com/mobxjs/mobx/pull/1964?

@loklaan Or is it possibly related to those Symbol changes? I wasn't really following that.

**Comment by idudinov** [comment] 2019-06-24 13:24
Thanks for considering this!

> Uh, can you elaborate on how TypeScript makes it more common? :) On the contrary, it could be rather annoying to correctly modify something like that.

I know that prototype extending is bad practice in general, using it in ES is not safe, leads to errors, so for ES users this bug would not be major at all. My point was about Typescript case, where such extending is type-safe, one can always track it, fix it etc., therefore it might be more spread, so there may be more cases when somebody like me encounters this issue.

<details>
  <summary>Typescript example for extending <b>Array.prototype</b></summary>

```typescript

declare global {
    interface Array<T> {
        someAsync(cond: (v: T, index?: number, arr?: T[]) => Promise<boolean>): Promise<boolean>;
    }
}

export async function someAsync<T>(this: T[], cond: (v: T, index?: number, arr?: T[]) => Promise<boolean>): Promise<boolean> {
    for (let i = 0; i < this.length; ++i) {
        const ok = await cond(this[i], i, this);
        if (ok) {
            return true;
        }
    }

    return false;
}

Array.prototype.someAsync = someAsync;
```

And now usages of it should be caught and understood by IDE.

</details>

That's not a blocker anyways, since one can stick to `5.9.4`.

**Comment by spion** [comment] 2019-06-24 15:42
The reason why extending prototypes is not safe is mainly because the language implementer might decide to add a method named exactly like yours some day.

**Comment by loklaan** [comment] 2019-06-24 19:53
If you're going to extend `Array.prototype` (I wouldn't recommend it) then you should copy the descriptors found on other proto functions like `concat`; essentially, make it non-enumerable.

Forgetting to do this means that any kind of array looping would include the `extension` property/value, which is the core issue here. I'd imagine this unexpected behaviour would break a lot of library & user land code..

@FredyC Yeah it's the cause - in the past we were looping over object props but now we are looping over an array of prop-keys extracted from the object.

**Comment by FredyC** [comment] 2019-06-24 20:33
@loklaan I suppose it depends if it's easy to fix. Otherwise, I don't think we want to overcomplicate code to support an edge case that not many people does these days. Sorry @idudinov, I suppose you will have to find some other way or stick to an older version for a while.

**Comment by idudinov** [comment] 2019-06-24 20:42
> If you're going to extend `Array.prototype` (I wouldn't recommend it) then you should copy the descriptors found on other proto functions like `concat`; essentially, make it non-enumerable.

@loklaan could you please elaborate on that? Am I able to do this in my code?

@FredyC not a problem, I understand.

**Comment by FredyC** [comment] 2019-06-24 20:45
@idudinov You have to use `defineProperty` to set `enumurable: false` so it won't be seen when looping over it. In contrast, that makes it less elegant to use so you can start refactoring to a more supported way :)

**Comment by loklaan** [comment] 2019-06-24 21:02
@idudinov I should have given an implementation example, sorry mate!

@FredyC I'd have to write some tests and give it a try because I'm unsure where we're expecting non-own properties to work (eg. from intentional user-land proto inheritance). I think I have time to put something together this week - could you assign this to me?

**Comment by FredyC** [comment] 2019-06-25 05:44
@loklaan Thanks! For some reason, I cannot assign you, not sure why.

**Comment by urugator** [comment] 2019-06-25 12:01
>  I'm unsure where we're expecting non-own properties to work

While the initial implementation used `for (let key in properties)` and therefore included inherited props, it would fail anyway on:
`const descriptor = Object.getOwnPropertyDescriptor(properties, key)!`
The fact that descriptor can be `undefined` is completely ignored. 
So imho this was just an oversight of the original implementation and inherited props shouldn't be included and were never supported.

**Comment by ilkkao** [comment] 2019-06-26 05:36
Seeing this error with Ember.js + mobx. I believe Ember still extends Array.

**Comment by ilkkao** [comment] 2019-06-26 05:38
What Ember does is explained well here: https://guides.emberjs.com/release/configuring-ember/disabling-prototype-extensions/

**Comment by loklaan** [comment] 2019-06-26 21:56
@urugator Oh yeah you're totally right, thanks for short-circuiting my exploration 😆

@FredyC No worries! PR is up

@ilkkao If you have the time, could you test #2023 against the error you're encountering for Ember? 🙏

**Comment by ilkkao** [comment] 2019-06-27 06:04
@loklaan tested, I don't see this error anymore

**Comment by mweststrate** [comment] 2019-07-17 20:21
Copied the tests to 4.13 / 5.13 and they pass indeed.

**Closed by mweststrate** 2019-07-17 20:21 UTC
Labels: bug, help wanted

**Comment by urugator** [comment] 2019-07-17 22:19
@mweststrate 
Note that we should still change the impl of `getPlainObjectKeys(object)`
[it includes inherited keys](https://github.com/mobxjs/mobx/blob/master/src/utils/utils.ts#L158)
[but then the key is used to obtain **own** descriptor](https://github.com/mobxjs/mobx/blob/master/src/api/extendobservable.ts#L84)
yielding undefined and later failing on [`descriptor.value`](https://github.com/mobxjs/mobx/blob/master/src/api/extendobservable.ts#L84)

It's also described [in this comment](https://github.com/mobxjs/mobx/pull/2023#issuecomment-506078746)

**Comment by mweststrate** [comment] 2019-07-19 19:13
Added a guard that extendObservable doesn't accept inheritance based property objects, as changing the behavior of getPlainObject keys sounds potentially more dangerous (it is also used by other api's to reflect on user input)
