### ISSUE TITLE
[mobx] Out of bounds read: 0

### ISSUE THREAD

**Issue by BiancaArtola** [mobxjs/mobx#2913] opened 2021-04-23 12:56 UTC
I am using Mobx `6.1.8` with React in my project. 

I have a store that has the following observable:

```
export class Store {
  organizations: Array<IOrganization> = [];

  constructor() {
    makeObservable(this, {
      organizations: observable,
      setOrganizations: action,
    });
  }


  setOrganizations = (organizations: IOrganization[]) => {
    this.organizations = organizations;
  };

}
```

When I used it in another class, I get the following error:
![image](https://user-images.githubusercontent.com/21174759/115874039-0aaac200-a41a-11eb-8cf4-96edff006f95.png)

The `slice()` doesn't work for me. Can you please help me?

**Comment by iChenLei** [comment] 2021-04-23 13:08
Can you share a minimal reproducation online demo(e.g. codesandbox / stackblitz? It's helpful for us to dig bug. Thanks

**Comment by iChenLei** [comment] 2021-04-29 03:21
no active feedback, just close this issue, reopen if necessary.

**Closed by iChenLei** 2021-04-29 03:21 UTC
Labels: ♺ needs-reproduction, 🐛 bug

**Comment by BiancaArtola** [comment] 2021-04-29 12:16
It was an issue that happens with a Material UI component. I really don't know why

**Comment by congshengwu** [comment] 2021-05-13 08:59
@BiancaArtola 
I also met this warning from MobX, and I found it's caused by that I didn't check the boundary of the observable array data when I try to access it. 

In your case it's organizations I think. I assume you try to access the observable data like `organizations[index]`, but without checking whether the index is out of bounds.

Maybe you can check you code, is there any similar code like below? Without checking bounds.
`
const name = organizations[2].name;
`

And if so, change it like below:
`
if (organizations.length > 2) {
    const name = organizations[2].name;
}
`

**Comment by BiancaArtola** [comment] 2021-05-13 11:59
Yeah, the issue was related to the fact that I was using the organization's array inside a Material Component (Select component no be more specific). So it looks like the Select component internally was trying to access position 0 of the array.

**Comment by NawarA** [comment] 2022-09-19 22:24
Please add a flag to disable this warning in production. 

It's okay in your development env to warn a developers, but in production, mobx needs to be silent about an array being empty, while a developer tries to read if anything is inside of it.

Please release a flag to disable in developer warnings in production
