### ISSUE TITLE
Computed Properties Are Evaluated Unnecessarily

### ISSUE THREAD

**Issue by mjewell** [mobxjs/mobx#1805] opened 2018-11-09 02:27 UTC
In certain cases, computed properties are re-evaluated despite that their values will never be used. I have only been able to reproduce it in the context of `observer`, but it may be possible using only plain mobx. While this is generally not an issue because computed properties should not have side effects, in my case it occurred when using mobx-state-tree, and that re-evaluation caused a read of a property in a mobx-state-tree node that was no longer alive, causing an error. This code sandbox demonstrates the example both with and without mobx-state-tree: https://codesandbox.io/s/yqrl5vmnw1

In the sandbox, the important thing to notice is the console logs look like this:

```
render app 
render child 
compute y 
stopped watching 
compute y 
render app
```

In both examples, we render the child component only once, and the child component is the only place that the computed value is referenced. Despite that, we trigger `compute y` twice. Stopping watching causes the app component to not render the child, but `compute y` still happens after that. In the MST example, you can see that this problem causes this error to occur:

`[mobx-state-tree][error] You are trying to read or write to an object that is no longer part of a state tree. (Object type was 'Child'). Either detach nodes first, or don't use objects after removing / replacing them in the tree. Use setLivelynessChecking("error") to simplify debugging this error.`

It appears as though most of the time mobx is intelligent enough to determine whether these properties need to be re-evaluated, but in this case it fails. Would it be possible to delay the evaluation of a computed property until it is actually accessed for the first time after one of its dependent observables changes instead of immediately after noticing the change?

**Comment by urugator** [comment] 2018-11-09 12:07
Firstly, provided reproduction requires a little tweek:
```javascript
// render is not sync, invoke action in callback
ReactDOM.render(<App />, rootElement, () => {
  counter.incrementX();
});  
```
For the actual problem:
Basically your assumption is that the `y` doesn't have to be recalculated, because the child reaction (depending on `y`) is disposed as a result of re-running the app (parent) reaction (depending on `watch`).
Meaning that one reaction depeds on the effect of another, however such behavior is not compatible with batching mechanism.
Both reactions (app and child) are invalidated before they have a chance to run. To find out whether child reaction should be invalidated, `y` must be recalculated first.
Both components are therefore scheduled for update, but react makes sure the parent component runs first and thefore prevets re-rendering of child - event though it's update is scheduled first.  

> instead of immediately after noticing the change

It actually isn't immediately (it happens after `stopped watching` even though `a` is modified before), but it's before any reaction effect (rendering) is fired.

**Comment by mjewell** [comment] 2018-11-09 14:52
Thanks for the response and for the suggested change to the reproduction.

It is not clear to me why `y` must be recalculated to find out whether the child reaction should be invalidated. If computed properties were lazily evaluated then react ensuring the parent is evaluated first would mean we would never even need to know the value of `y`, since that is only used by the child and the child reaction seems to be prevented correctly in this case.

> instead of immediately after noticing the change

To clarify here, I understand that the reactions don't run until the action is complete, but I was referring to the fact that `y` is recalculated before any reactions (the render functions) run, so whether it is being depended on or not is based on a potentially outdated version of the world

**Comment by urugator** [comment] 2018-11-09 16:47
> It is not clear to me why y must be recalculated to find out whether the child reaction should be invalidated.

From Mobx perspective there is no relation between the reactions. It doesn't know that one reaction causes re-rendering of the parent, which subsequently causes re-rendering of the child.
It only knows that one reaction depends on `watch` and another reaction depends on `y`.
These are two seperate, independent reactions.
If `watch` is changed parent reaction must be notified.
If `y` is changed child reaction must be notified. 
But how do you know that that `y` actually changed without re-calculating it?
Again, Mobx doesn't know that child would be re-rendered (or unmounted) due to a change of `watch`. It doesn't know that one reaction is affected by another reaction...

Note that once react starts rendering, the Mobx can't call any more `setState/forceUpdate`. So all affected components must be forced to update before the first invalidated component starts with rendering. Meaning that all affected reactions must be called, before the rendering starts. Therefore the child reaction must be invalidated (causing Y to recalculate), before the parent starts with render.

> based on a potentially outdated version of the world

Well sort of ... it's because of the batching ... it's not easy to explain as it involves both mobx batching and reacts batching. However if you disable both (remove `@action` and invoke `incrementX` from `setTimeout`), you will prevent the second recomputation (at the cost of more rendering).

**Comment by mjewell** [comment] 2018-11-09 18:59
I see. So mobx needs to evaluate the computed property `y` to know if the child reaction should even be rerendered by react, because if its value didn't change the reaction does not need to happen. It's better for mobx to avoid running the reaction in the case that the computed did not change than for it to run the reaction only to find out that the computed has stayed the same and the reaction was unnecessary.

On top if this, since mobx does not know about the parent-child relationship, it cannot know what order to run the reactions in. Instead, it marks all affected reactions as needing to be re-run and passes that information to react, which determines which ones will actually run based on the parent-child relationships. Is my understanding correct (although probably very simplified)?

One final question, although it's only tangentially related. The error message says to use `setLivelynessChecking("error")` to simplify debugging, but when I set that the error message just goes away... Is that a separate bug with the liveliness checking of mobx-state-tree? Or is it related to this specific case of re-evaluating computed properties?

**Comment by urugator** [comment] 2018-11-09 20:45
> Is my understanding correct

I think so. Perhaps a following pseudocode could roughly demonstrate the behavior (note I may not be 100% correct either):  

```javascript
// After first render:
const parentReaction = reaction(() => watcher.watch, () => parent.forceUpdate())
const childReaction = reaction(() => counter.y, () => child.forceUpdate())

// During incrementX() call  
scheduleReaction(childReaction); // caused by possible change of y  
scheduleReaction(parentReaction); // caused by change of watch

// After incrementX() - end of transaction
// https://github.com/mobxjs/mobx-react/blob/611abe46cdaf82449f2aa0a3c75e30c26837db90/src/index.js#L9
ReactDOM.unstable_batchedUpdates(() => {
  runScheduledReactions();  // the y is forced to recompute here I believe, not exactly sure...  
})

// now it's react turn to find out which component update first
```

> mobx-state-tree

Unfortunately I am not familiar with mobx-state-tree, so someone else will have to help with this one.
However I tried to change the computed like this
```javascript
get y() {
  console.log("compute y start");      
  const length = getParent(self, 2).children.length;
  console.log("computed y end", length);
  return self.x + length;
}
```
and the result was quite weird -  error dissapeared, but computation doesn't seem to finish...

**Comment by urugator** [comment] 2018-11-10 00:39
> Would it be possible to pass all potentially affected reactions to react instead based solely on observable data (and not computed properties),

All components may depend solely on `computed` values. So all your components can be potentially affected. What is going to cause "the react reevaluation/render"? You have to invalidate some component by calling `setState/forceUpdate`, which one?
The reaction's effect must be `setState/forceUpdate` call. If you want to delay the recomputation, you have to delay the reaction and therefore you will delay the effect (`setState/forceUpdate`) as well.
So if recomputation should occur during render and not before, then also effect would occur durign/after render.
But calling `setState/forceUpdate` is not allowed during render phase - as it would schedule yet another update (making batching meaningless).
If you can't run effects during render, you can't delay reactions, thefore you can't delay computations.

**Comment by mweststrate** [comment] 2018-11-16 16:19
The problem here is that we have to evaluate `y` to determine whether we would need to schedule `Child` for a re-render (add it to to the queue of pending reactions).

There are a few possible strategies
1. Don't evaluate `y`, just _assume_ it has changed, and always schedule all `Child` components. That is bad, because if `Parent` didn't remove actually remove, `Child` would always re-render, even if it didn't change
2. Evaluate `y`, schedule `Child` only if `y` changed. Even tough `Child` might never actually run, for it being aborted by `Parent` This is the current behavior. 
3. Schedule a possible run of `Child`. Schedule a run of `Parent`. If after `Parent` run `Child` is still alive, compute and check if `y` did actually change, re-render `Child` based on that. This has a few problems
   1. How long does `mobx` have to wait until it can decide whether `Parent` did or did not abort `Child`? Rendering is an async process, so there is no easy answer to that
   2. Even if we could somehow solve 1, On top of that, as urugator indicated, mobx doesn't know about the parent / child relationship. For mobx these are not `Parent` and `Child`, but just reactions `X` and `Y`, and it can't predict whether `X` might be abort `Y`, or `Y` might abort `X`, or that both could even abort each other (which is not possible with components, but it is with reactions in general). 

I hope that explains the current behavior. If your PR solves this, could you demonstrate that in an updated sandbox? (you could publish mobx under your own namespace in npm to make that easy)

**Comment by mayorovp** [comment] 2018-11-16 20:36
@mweststrate done: https://codesandbox.io/s/myojz5no29

**Comment by mweststrate** [comment] 2019-01-21 12:54
@mayorovp played a bit with it, I think the following approach could achieve the same, without the need for a second type of reaction (didn't test yet!)? https://codesandbox.io/s/7314146n8x (in that case, shouldCompute should be exposed on `ComputedValue`, which is a much smaller chagne)

**Comment by mayorovp** [comment] 2019-01-21 13:45
@mweststrate i see this log in the console by your link:

*** regular example start *** 
render app 
render child 
compute y 
stopped watching 
compute y 
render child 
render app

This is worse than ever current behavior! Not only `y` was computed unnecessarily, but child was rendered...

**Comment by mweststrate** [comment] 2019-03-14 09:18
Closing, although I really enjoy the brainstorming and analysis, I don't think adding a second derivation model at this stage of the project justifies the additional complexity in implementation and mental model of users using it.  See also this [comment](https://github.com/mobxjs/mobx-react/issues/640#issuecomment-465067305)

**Closed** 2019-03-14 09:18 UTC
