### ISSUE TITLE
Make autorun schedule effect without running it the first time?

### ISSUE THREAD

**Issue by AriaFallah** [mobxjs/mobx#207] opened 2016-04-21 02:55 UTC
In my experience, when I've first used `autorun` to schedule an effect, it runs that effect that one time regardless of whether or not the observable has mutated.

Is there a way to schedule an autorun, but without running it?

**Comment by mweststrate** [comment] 2016-04-21 05:27
That first run is always needed, otherwise MobX won't be able to detect which data it depends upon. But it is quite common to not needing the side effects of an autorun the first time. You can use a simple flag to avoid that:

```javascript
var myData = observable({ some data })
var firstrun = true;

autorun(() => {
  // we do want to know which data this autorun depends on after the first run
  var data = serializeStuff(myData)
  if (firstrun)
    firstrun = false
  else
    // but we only need the effect to happen after the first run
    sendDataToServer(data)
})
```

Since this is not an uncommon pattern, I guess it makes sense to have `autorun` pass an optional `firstrun` param in. That would make it possible to just write the following:

```javascript
var myData = observable({ some data })

autorun((firstrun) => {
  var data = serializeStuff(myData)
  if (!firstrun)
    sendDataToServer(data)
})
```

Makes sense?

**Comment by AriaFallah** [comment] 2016-04-21 12:18
@mweststrate why reopen? I thought both your solution, and your proposal to update autorun in the feature were good ideas.

**Comment by mweststrate** [comment] 2016-04-21 12:22
@AriaFallah exactly, so to not forget about adding it in the feature I reopened it.

Ok, that is weird probably, I'll close this one and create a new one :-P

**Comment by mweststrate** [comment] 2016-04-21 12:23
...and close!

**Closed by mweststrate** 2016-04-21 12:23 UTC
Labels: question

**Comment by yiakwy** [comment] 2018-03-14 15:43
@mweststrate I am actually doing exactly the same thing. What lead me to the page is that I have jason like observable in store (a bunch of observable instances) a script in mobx-observable/state.js, which is very large:

```
@observable options = {
   A:  {
   },
   B: {
    }
}
```
## problem discription

(1)

I have two methods call BuildMap (depends on options.A, options.B), and BuildRoadNetwork (depends on options.B).

When programme set up, BuildMap, will build map and build roadnetwork on top of map just as what BuildRoadNetwork does.

That means, when Options.A, options.B changed, BuildMap will be fired. Options.B means when I build map I need to pass Options.B to build roadnetwork.

(2)

But sometimes, user want to modify the roadnetwork without changing the whole map, hence I provide him method BuildNetwork.

That means, when options.B changed, BuildRoadNetwork will be fired.

## problems

Now you see what the problem is: 
(1) When programm set up: BuildNetwork will be fired twice.
(2) When Options.B changes: the BuildMap will be fired (side effect)

So I have to remove options.B from BuildMap dependancy (by refer it in untracked methods), but that breaks mobx wonderful automatical dependency chain.

Hope you save me life!

**Comment by yiakwy** [comment] 2018-03-15 07:53
@AriaFallah @mweststrate

**Comment by mweststrate** [comment] 2018-03-15 10:51
@yiakwy please don't ask new questions in closed questions. 

Also, don't start tagging people if they don't answer questions quickly enough to your liking. It is quite offensive. Free stuff doesn't come with an SLA.

**Comment by yiakwy** [comment] 2018-03-16 04:02
@mweststrate I  mean no offense to you. I was not complaining simply because no quick response. I thought that you are a busy man (because your contribution), github notifcations might be to much for you see it.
