### ISSUE TITLE
ten minute guide: examples execution is slightly out of order

### ISSUE THREAD

**Issue by neil-rubens** [mobxjs/mobx#634] opened 2016-10-28 23:05 UTC
https://mobxjs.github.io/mobx/getting-started.html

`run code` seems to execute slightly out of order (by 1); e.g.: 

in the section `A simple todo store...` executing the first example will print to the console (but that should be done when executing the second example).

or executing examples in the `Making React reactive` already shows icons for assignees (something that is added in the next section)

p.s. `mobx` seems great; am looking froward to using it.

**Comment by mweststrate** [comment] 2016-10-31 18:57
The examples in the 10 minute tutorial are indeed somewhat confusing, especially when you don't read them carefully. They could benefit from some additional love :)

**Comment by neil-rubens** [comment] 2016-11-04 06:18
The examples are good; just the execution button is slightly out of order.

I can try to update the doc; however I couldn't find the `getting-started.html` in repo.

**Comment by mweststrate** [comment] 2016-11-04 07:12
it is in the gh-pages branch. thanks in advance!

Op vr 4 nov. 2016 07:18 schreef Neil Rubens <notifications@github.com>:

**Comment by hugows** [comment] 2017-01-06 14:13
I coudn't understand this one - shouldn't "try MobX" appear on the console log?

![image](https://cloud.githubusercontent.com/assets/11545/21720301/6f7ed7f6-d409-11e6-8a1e-0d82a44dd2f5.png)

**Comment by mweststrate** [comment] 2017-01-07 09:24
No, the report function only prints the the title of the _first_ todo, so
changing the title of the second todo won't affect the report, hence it is
not printed

Op vr 6 jan. 2017 om 15:13 schreef Hugo Schmitt <notifications@github.com>:

**Comment by hugows** [comment] 2017-01-08 11:14
Thank you, sorry for the noise.

**Comment by eladnava** [comment] 2017-01-17 19:17
I would love to give this a shot. 👍

**Comment by eladnava** [comment] 2017-01-17 21:00
I was able to reproduce the issue with the first `Run` button in `A simple todo store...`. It simply isn't necessary there, since that code outputs nothing when it is executed. 

```js
const todoStore = new TodoStore();
```

But the code section after that does emit output, so that one should have a `Run` button:

```js
todoStore.addTodo("read MobX tutorial");
console.log(todoStore.report());

todoStore.addTodo("try MobX");
console.log(todoStore.report());

todoStore.todos[0].completed = true;
console.log(todoStore.report());

todoStore.todos[1].task = "try MobX in own project";
console.log(todoStore.report());

todoStore.todos[0].task = "grok MobX tutorial";
console.log(todoStore.report());
```

I could not reproduce the behavior you mentioned with the already showing assignee icons.

**Comment by eladnava** [comment] 2017-01-18 11:48
Apparently PR #647 is also related to this issue.

**Comment by mweststrate** [comment] 2017-02-03 21:56
Those PR's has been released, closing the issue

**Closed by mweststrate** 2017-02-03 21:56 UTC
Labels: help wanted, ready-to-be-implemented-by-volunteer
