### ISSUE TITLE
Proxies Array.map Empty 

### ISSUE THREAD

**Issue by mbrahimi617** [mobxjs/mobx#2061] opened 2019-07-30 04:07 UTC
So I have an application which makes use of a backend API for CRUD operations of some data. I've created a store to handle this data and render it accordingly by using an observable array like so:

<pre>
@observable data = []; 
</pre>

Of course, I have a `setData` action to actually update the data instead of trying to directly change the data in response callbacks. It appears the data is being properly fetched as indicated by the length of `[[Target]]` in the proxy which wraps the observable array. However, if I try to use a `map` function on the injected data in my component, I get nothing. None of the attributes can be extracted from the objects contained within, not the id nor the fields of the DB model. Absolutely nothing will render, and I'm very confused how to actually render the initial data from the first fetch and continue to do so on subsequent changes.

**Comment by mbrahimi617** [comment] 2019-07-30 05:13
I've done some debugging by adding a test object to the array manually in the action and it appears to be working. That would only seem to indicate that there is an issue in actually setting the data following the HTTP request. From what I can tell, everything in my action looks fine:

<pre>

@action fetchTables = () => {

  axios.get("/api/firmware/")

    .then((resp) => {

      runInAction(() => {

        this.data.replace(resp.data);

      });

    });

  };
</pre>

**Comment by urugator** [comment] 2019-07-30 08:34
Ain't you returning `{ data: [] }` from your API by any chance? It would be `resp.data.data` ...

What does the following yield?:
```javascript
@action fetchTables = () => {
  axios.get("/api/firmware/")
    .then(action(resp => {
        console.log(resp.data); // <-- THIS
        this.data.replace(resp.data);
        console.log(toJS(this.data)); // <-- THIS
    }));
};
```

**Comment by mbrahimi617** [comment] 2019-07-30 14:59
This is entirely equivalent because `runInAction` is just syntactic sugar. Like I said, the API returns successfully with a 200 response. Even after the array replacement, the data appears to be there from a console log. But no I'm not noob enough to nest the data in a JSON key `data`. The response is a top level list.

**Comment by urugator** [comment] 2019-07-30 15:32
It's supposed to be entirely equivalent... I am simply asking about the output, since you haven't provided working reproduction...

**Comment by mbrahimi617** [comment] 2019-07-30 15:34
The output is the list from the response and it's way too large and nested to dump here. I think I have figured out the issue. Essentially, I was using arrow functions for React Lifecycle methods like `render` which caused Mobx to be unable to pass down props to the proper context because of flawed binding.

**Comment by urugator** [comment] 2019-07-30 16:43
Yes, arrow functions as lifecycle methods are not supported on `observer`.
Please close the issue if that resolves your problem, otherwise feel free to elaborate.

**Closed** 2019-07-30 21:10 UTC
