### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by danceasarxx** [mobxjs/mobx#85] opened 2016-01-03 21:49 UTC
Could you please make effort to host it on bower. I have my build tool(gulp + browserify + babel) setup to use bower as a repository of vendor dependencies

**Comment by richotaylor** [comment] 2016-01-04 17:17
+1

**Comment by mweststrate** [comment] 2016-01-05 08:51
I added the package to bower @danceasarxx. Can you verify the current setup is working as expected?

**Comment by danceasarxx** [comment] 2016-01-13 04:13
Yup, yup, yup..it's there. Thanks a lot

**Comment by mweststrate** [comment] 2016-01-16 19:01
Apologies, forgot to push a new tag. Should be fixed now

**Comment by PhiLhoSoft** [comment] 2016-03-30 14:26
Head ups:
`bower lookup mobx` answers "Package not found".
If I search on bower.io (http://bower.io/search/?q=mobx), I get the mobservable entry...
Indeed, `bower lookup mobservable` answers "mobservable git://github.com/mweststrate/mobservable.git".
`bower home mobservable` answers:
```
bower mobservable#*         not-cached git://github.com/mweststrate/mobservable.git#*
bower mobservable#*            resolve git://github.com/mweststrate/mobservable.git#*
bower mobservable#*           download https://github.com/mweststrate/mobservable/archive/2.0.4.tar.gz
bower mobservable#*            extract archive.tar.gz
bower mobservable#*           resolved git://github.com/mweststrate/mobservable.git#2.0.4
```
so it looks reasonably up-to-date...
Apparently, Bower hasn't updated fully to the new bowser.json file, or something like that.

**Comment by PhiLhoSoft** [comment] 2016-03-30 15:01
I stand corrected. After Bower installation, I get no single `.js` file to load in our project. Nothing at root, not `dist` folder, etc. Not sure how to deal with that. We don't want to use a CDN...

**Comment by mweststrate** [comment] 2016-03-30 18:23
I'll take a look tomorrow!

Op wo 30 mrt. 2016 om 17:01 schreef Philippe Lhoste <
notifications@github.com>:

**Comment by PhiLhoSoft** [comment] 2016-03-30 21:05
Thanks. I would love to add MobX to our AngularJS project, still relying on Bower for front-end libraries, and using Jenkins for auto-build on CI server, so we can't tinker with original files and what's not. Apparently we need your UMD build, as I used in http://plnkr.co/edit/QGhtGu

As I struggled all day with complex UI state (toolbar button disabling depending on several asynchronous (or not) conditions), I would love to use MobX to clean up this mess... :laughing: 

Note: maybe this article can help you: https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564#.b0u1b929h

**Comment by mweststrate** [comment] 2016-03-31 13:10
@PhiLhoSoft yes preferrably the UMD builds are not available through github, does `bower install https://npmcdn.com/mobx/lib/mobx.umd.js` work for you? I'll figure out whether that can be standardized through bower.

**Comment by mweststrate** [comment] 2016-03-31 13:41
Even better: `bower install https://npmcdn.com/mobx/bower.zip`

**Comment by mweststrate** [comment] 2016-03-31 21:24
@PhiLhoSoft is the above link sufficient as bower installation? It seems that bower provides no installation mechanism that doesn't require storing a generated umd build in git (which is an ugly thing to do imho)

**Comment by andykog** [comment] 2016-03-31 21:29
The only way to deal with this is having seperate repo for bower, like git://github.com/facebook/react-bower.git

**Comment by PhiLhoSoft** [comment] 2016-03-31 21:34
I did a quick test at home, `bower install https://npmcdn.com/mobx/bower.zip` delivers the `mobx.umd.js` file, so it looks OK.
I will do a test tomorrow, at work. Many thanks for the quick answer.

**Comment by PhiLhoSoft** [comment] 2016-04-04 12:14
If that's not too much asking, it would be nice to include a `mobx.umd.min.js` (and probably its corresponding .map file) in this Zip file. Thanks.

**Comment by mweststrate** [comment] 2016-04-11 19:34
Updated the build scripts accordingly. Will be available from the next release (I can release it if you need it now)

**Closed by mweststrate** 2016-04-11 19:34 UTC

**Comment by mweststrate** [comment] 2016-04-15 02:43
@PhiLhoSoft, done, the file should be available now (from v 2.1.3)

**Comment by PhiLhoSoft** [comment] 2016-04-15 08:34
Ah, sorry, but I can see the minified file at https://npmcdn.com/mobx@2.1.3/lib/, but for some reason, npmcdn doesn't package it in its bower.json (https://npmcdn.com/mobx/bower.zip).

We should really move out of using Bower, but currently we are stuck with it... :grimacing:

**Comment by mweststrate** [comment] 2016-05-30 12:19
`Server error: ENOENT: no such file or directory, lstat '/tmp/npm-http-server-mobx@2.2.2/tmp/npm-http-server-mobx@2.2.2/bower.zip'` on https://npmcdn.com/mobx@2.2.2/bower.zip

@PhiLhoSoft seems like an issue on npmcdn to me at first sight: `/tmp/npm-http-server-mobx@2.2.2/tmp/npm-http-server-mobx@2.2.2/bower.zip` should probably be `/tmp/npm-http-server/mobx@2.2.2/bower.zip` or something...

cc: @mjackson

**Comment by PhiLhoSoft** [comment] 2016-05-30 12:38
Yes, I pinged @mjackson via Twitter about this issue.
Meanwhile, I bite the bullet and get MobX (and another library with lesser Bower support) via npm, then copied the files among the other Bower libraries via Gulp (already had a `gulp.js` in my Maven-based build process, anyway):
```
gulp.task('copy-libs', function()
{
	gulp.src('./node_modules/mobx/**/*.*')
		.pipe(gulp.dest('./src/main/webapp/assets/libs/mobx'));
	gulp.src('./node_modules/ally.js/*.*')
		.pipe(gulp.dest('./src/main/webapp/assets/libs/ally.js'));
});
```
Seems to work so far... (easier because of no dependencies).
Would probably be a good idea to drop Bower entirely, anyway, but that's some work.

**Comment by mjackson** [comment] 2016-05-30 15:08
Ah, sorry for the regression. It's [fixed](https://github.com/mjackson/npm-http-server/commit/ae0f9387999fd1933b91e466fda07adf9d0629c0) now.

> Would probably be a good idea to drop Bower entirely

Yep :)

**Comment by mweststrate** [comment] 2016-05-30 15:20
Awesome, thanks!

Op ma 30 mei 2016 17:08 schreef Michael Jackson <notifications@github.com>:
