### ISSUE TITLE
@computed does not work for static fields

### ISSUE THREAD

**Issue by aravantv** [mobxjs/mobx#351] opened 2016-06-21 22:31 UTC
The following Typescript code:

``` typescript
class Comp extends React.Component<{}, {}> {
    @observable public static x: number
    @computed public static get x2() {
        return Comp.x * 2
    }
    public render() {
        return <div>{Comp.x2}</div>
    }
}
```

followed by a simple rendering of Comp yields immediatly the following error:

`Uncaught TypeError: Cannot redefine property: $mobx`

(note that you don't even need to decorate the class with "`@observer`")

**Comment by aravantv** [comment] 2016-06-24 09:17
Any comment on this? Can you reproduce? Can I help somehow?

**Comment by mweststrate** [comment] 2016-06-24 09:46
The issue is clear, thanks :) The behavior of `@observable` is not defined yet in two cases:
1. on `static` fields
2. on object literals (`var vector = { @observable x: 3, @observable y: 4 }`) (see #358)

I will check whether this are feasible options and pending that outcome will decide and document these cases in the docs.

Note that in the mean the following workaround should be able to help you out:
`extendObservable(Comp, { x: 0, x2: () => Comp.x * 2 })`

For typings sake you could declare Comp static members as: `public static x: number; public static x2: number;`

I'll come back to this one, sorry for not responding earlier!

(N.b, note that you don't initialize `x` in your test case)

**Comment by aravantv** [comment] 2016-06-24 09:53
Great, thanks for the answer and the workaround!

I actually have my own workaround which works well in my context at the moment.

Regarding not initializing x, it does not actually matter on this example since rendering occurs anyway before initialization of the static field (! this is actually I think a typescript compilation issue, but I did not have the time to investigate this), sorry for not pointing it out.

**Comment by Loilo** [comment] 2016-09-20 22:15
@aravantv Would you mind to post your workaround here?
The one provided by @mweststrate does not work for me so far.

It says "[mobx] Invariant failed: extendObservable expects an object as first argument".
I looked up the source code and realized that the class (by being a function) naturally fails the "typeof myclass === 'object'" test even if a function is an object too. :)

**Comment by aravantv** [comment] 2016-09-21 08:54
Unfortunately, my workaround is probably not satisfying for you: I just stopped using classes and use only plain functions instead... So a significant change of the architecture of your code.

**Comment by Loilo** [comment] 2016-09-21 09:07
Well I actually did a similar thing by moving the static properties before the class as normal variables. That's not pretty, but it works. Thanks anyway. :)

**Comment by mweststrate** [comment] 2016-09-29 09:27
@aravantv  / @Loilo just wondering, does the following pattern work as work around?:

```javascript
extendObservable(Comp.prototype, {
   x: 3,
   get x2() {
     return Comp.x * 2
  }
})
```

**Comment by alidavut** [comment] 2016-11-22 03:17
If this is fixed we can use both store and model with a single class.

```js
class Product {
  @observable static items = [];
  @observable name;

  @computed
  static get drafts() {
    return this.items.filter(i => i.draft);
  }
}
```

```js
Product.drafts // => [....]
const product = new Product();
....
```

**Comment by diiq** [comment] 2017-05-02 01:37
Sorry, @mweststrate, the `.prototype` wheeze doesn't seem to work either -- at least, not if you ever plan on setting `Comp.x`, which of course you *do* plan to do, that's why you're making it observable :)

You could maybe faff about even further and add a setter for Comp.x that actually sets Comp.prototype.x? Haven't tried that yet, though, because it seems simpler and clearer to fake out the static values with a separate singleton for now, and wait for @observable to support static properties :)

**Comment by mweststrate** [comment] 2017-05-02 10:01
@diiq, apologies, should be `extendObservable(Comp, { ...}))`, *not* the `.prototype`. Emulating static members keeps being weird in JS ;-)

**Comment by diiq** [comment] 2017-05-02 12:11
Ah, sorry, @mwestrate, as Loilo mentions above, that doesn't seem to work when Comp compiles to be a function -- it fails an assertion. But thanks!

A separate singleton, and a static getter and setter is the only thing I've found to work so far.

**Comment by mweststrate** [comment] 2017-10-05 18:49
Closing for now. Can be reopened in the future when Typescript & Babel implement the new decorator semantics.

**Closed by mweststrate** 2017-10-05 18:49 UTC
Labels: waiting-for-standardized-decorators

**Comment by omerman** [comment] 2019-05-13 14:26
If someone comes here.. I would like to say that I checked and this syntax works:

```
class MyClass {
@observable
static myObservable = {}
}
```
