### ISSUE TITLE
Are the docs broken?

### ISSUE THREAD

**Issue by Obiwarn** [mobxjs/mobx#1814] opened 2018-11-15 11:38 UTC
When I enter via https://mobx.js.org

![image](https://user-images.githubusercontent.com/9539797/48550481-2584be00-e8d3-11e8-88a8-65f8e4f11c34.png)

and then click a link in the navmenu on the left the menu gets cluttered up like this:

![image](https://user-images.githubusercontent.com/9539797/48550422-02f2a500-e8d3-11e8-9199-1037b1452ae5.png)

_Originally posted by @Obiwarn in https://github.com/mobxjs/mobx/issue_comments#issuecomment-439011248_

**Comment by mweststrate** [comment] 2018-11-16 15:56
https://mobx.js.org/refguide/ is a 404 for me?

**Comment by jlgrall** [comment] 2018-11-18 14:09
At the top of the menu, I see that the search field contains "nested". So the menu only shows pages that contain the search string. That is normal behavior.

**Comment by Obiwarn** [comment] 2018-11-19 09:13
Ok I could reproduce it (thanks to @jlgrall). 

@mweststrate sorry wrong link (changed it).

So the thing is (which I find a bit weird, so this could be somehow a bug):
1. go to https://mobx.js.org/index.html
2. press search icon & enter e.g. "zulu"
3. now hide search  (press search icon => regular sidebar appears)
4. now follow a link in the sidebar
5. now the search filter is active again (i.e. hidden sidebar items)

**Comment by ItamarShDev** [comment] 2018-11-19 12:11
Can be easily reproduced.
The question is - what it on purpose (by design) and if yes, why?
if not, what should be the solution?
@mweststrate

**Comment by ItamarShDev** [comment] 2018-11-19 12:31
@mweststrate that what I thought too :P
If it cant be fixed, this issue should be closed?

**Comment by mweststrate** [comment] 2018-11-19 13:00
yep, with 'wontfix' label

Op ma 19 nov. 2018 om 13:31 schreef itamar sharify <notifications@github.com

**Comment by jlgrall** [comment] 2018-11-19 13:57
GitBook version on https://mobx.js.org/ is 2.4.3 (see meta generator in page source).
Latest GitBook version is [2.6.9](https://github.com/GitbookIO/gitbook/releases).

So maybe updating to the latest version of gitbook can resolve this issue.

**Comment by ItamarShDev** [comment] 2018-11-19 16:52
Sounds like a good idea

**Comment by mweststrate** [comment] 2018-11-30 15:59
Regenned with the latest version. HOpefully this fixes the issue

**Closed** 2018-11-30 15:59 UTC
