### ISSUE TITLE
when uses [...array] appear issue

### ISSUE THREAD

**Issue by Joey-Huang** [mobxjs/mobx#1395] opened 2018-03-13 02:56 UTC
Welcome to MobX. Please provide as much relevant information as possible!

I have a: Issue:
```
class AppState{
   @observable data:string[] = [];

    add(text: string) {
        this.data = [text,...this.data];
        console.log(JSON.stringify(this.data));
    }
}

export const appState = new AppState();

appState.add("test1");//log ["test1",[]]                   hope:["test1"]
appState.add("test2");//log ["test2",["test2",[]]]      hope:["test2","test1"]
```

**Comment by mweststrate** [comment] 2018-03-13 11:57
This will be fixed in MobX 5, before that, you have to slice your data `...this.data.slice()` before concat / spreading it. (See also https://mobx.js.org/best/pitfalls.html#-array-isarray-observable-1-2-3-false)

But in this specific case, there is no need at all to construct a new array and assign that to `this.data`, it is needlessly expensive, with MobX you can just do `this.data.unshift(text)`

**Comment by urugator** [comment] 2018-03-13 17:44
@mweststrate Are you sure it doesn't relate to changes done in ObservableArray iterator? In Mobx 3 spreading works...

**Comment by mweststrate** [comment] 2018-03-14 09:46
@urugator you are right, because the iterator returned an real array (not just an iterator) in MobX 3, a weird effect of that is that spreading did work... 

We can fix that quite easily by implementing `Symbol.isConcatSpreadable` on observable arrays. The downside; it doesn't work on Internet Explorer, which is not acceptable for MobX 4 i think.

So the solutions for now is to `...this.data.slice()`. Will mention it in the changelog.

For people who don't care about IE, the fix is:

```
Object.defineProperty(observable([]).constructor.prototype, Symbol.isConcatSpreadable, {
   enumerable: false, configurable: true, value: true
})
```

**Comment by mweststrate** [comment] 2018-03-14 10:07
@Joey-Huang https://github.com/mobxjs/mobx/commit/0d73fdd763650c01f9890169829ded9e5480bd8b, arrays are in principle spreadable in MobX 4. On what browser / environment are you experiencing this problem?

**Comment by mweststrate** [comment] 2018-03-28 18:05
Closing for the lack of a reproduction

**Closed by mweststrate** 2018-03-28 18:05 UTC
Labels: cannot reproduce

**Comment by gnimmelf** [comment] 2018-12-10 13:46
Sorry for co-opting and late arrival =)

Seems `unshift` is not working, whereas `push` does. 

"mobx": "^5.7.0", CRA without decorators, so:

```
decorate(MyClass, {
  myArray: observable,
})
```

Meanwhile elsewhere:
`this.props.store.myArray.unshift(newItem);` <= No reaction
`this.props.store.myArray.push(newItem);` <= Works as expected

I'm brand new to mobX, but in a hurry, so please bear with me if I am really stupid.

Thanks for your time and mobX!
