### ISSUE TITLE
mobx-undecorate failed with .tsx files

### ISSUE THREAD

**Issue by shizuku** [mobxjs/mobx#2513] opened 2020-10-13 16:30 UTC
I have a react and typescript project using mobx, when migrate to mobx6 using mobx-undecorate, i find it seems not support jsx for typescript.
```
......
......
 ERR /home/shizuku/workspace/electron/muse-electron/src/renderer/components/muse-notation/MuseNotation.tsx Transformation error (Unexpected token, expected "," (133:6))
SyntaxError: Unexpected token, expected "," (133:6)
    at Object._raise (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:60:45)
    at Object.raiseWithData (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:55:17)
    at Object.raise (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:39:17)
    at Object.unexpected (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/util.js:139:16)
    at Object.expect (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/util.js:116:28)
    at Object.tsParseDelimitedListWorker (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:272:16)
    at Object.tsParseDelimitedList (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:232:14)
    at Object.tsParseBracketedList (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:294:27)
    at Object.tsParseTypeParameters (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:394:26)
    at /home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:2405:31
 ERR /home/shizuku/workspace/electron/muse-electron/src/renderer/components/muse-notation/MuseNote.tsx Transformation error (Unexpected token, expected "," (347:7))
SyntaxError: Unexpected token, expected "," (347:7)
    at Object._raise (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:60:45)
    at Object.raiseWithData (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:55:17)
    at Object.raise (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:39:17)
    at Object.unexpected (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/util.js:139:16)
    at Object.expect (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/util.js:116:28)
    at Object.tsParseDelimitedListWorker (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:272:16)
    at Object.tsParseDelimitedList (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:232:14)
    at Object.tsParseBracketedList (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:294:27)
    at Object.tsParseTypeParameters (/home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:394:26)
    at /home/shizuku/.npm/_npx/55618/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:2405:31
All done. 
Results: 
7 errors
0 unmodified
5 skipped
0 ok
```
the position of  SyntaxError is exactly the jsx tag.

**Comment by mweststrate** [comment] 2020-10-13 16:49
Duplicate of #2501, will try to release a fix later this week. Or feel free to take a stab at the proposed solution.

**Closed by mweststrate** 2020-10-13 16:49 UTC
Labels: bug
