### ISSUE TITLE
[mobx6] action.bound decorator not bounding when using makeObservable(this) and an unassigned observable

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx#2467] opened 2020-09-30 17:53 UTC
```ts
import { observable, action, makeObservable } from "mobx"

class C {
  @observable
  x!: number // if assigned here (= 0) then it works ok

  @action.bound
  incX() { this.x++ }  

  constructor() {
    // this.x = 0 // if assigned here then it works ok
    makeObservable(this)
    this.x = 0 // if assigned here then it breaks
  }
}

const c = new C()
c.incX.apply(undefined) // error, "this" is undefined (since it is not actually bound)
console.log(c.x)
```

**Comment by xaviergonz** [comment] 2020-09-30 18:01
Code sandbox: https://codesandbox.io/s/small-tree-d9bj0?file=/src/index.ts

**Comment by mweststrate** [comment] 2020-09-30 18:43
I assume this is caused by the same issue as #2468, let me know if it still breaks after updating the build config

**Comment by mweststrate** [comment] 2020-10-03 19:42
Closing this for now.

**Closed by mweststrate** 2020-10-03 19:42 UTC
Labels: bug

**Comment by merry75** [comment] 2020-10-06 18:58
not working still even if we assigned an @observable, the @action decorator will not work when using makeautoobservable mobx6

**Comment by mweststrate** [comment] 2020-10-06 19:36
@merry75 this issue is closed, please open a new issue and follow the template. "not working" comments without reproduction are inactionable for us.

**Comment by mweststrate** [comment] 2020-10-17 22:10
Update: this issue was caused by a babel / typescript integration bug, make sure to use Babel 7.12 or higher.
