### ISSUE TITLE
TypeScript: @observer should work with React.Component<void, void>

### ISSUE THREAD

**Issue by tkrotoff** [mobxjs/mobx#665] opened 2016-11-18 11:37 UTC
`@observer` does not like TypeScript `React.Component<void, void>`, example:

```TypeScript
@observer // TypeScript error
class FooBar extends React.Component<void, void> {
  render() {
    return <div />;
  }
}
```

```
error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<void>' is not assignable to type 'typeof FooBar'.
    Type 'Component<void, ComponentState>' is not assignable to type 'FooBar'.
      Types of property 'render' are incompatible.
        Type '() => Element | null' is not assignable to type '() => Element'.
          Type 'Element | null' is not assignable to type 'Element'.
            Type 'null' is not assignable to type 'Element'.
```

Replacing `React.Component<void, void>` by `React.Component<{}, void>` works (no TypeScript error):
```TypeScript
@observer // No TypeScript error
class FooBar extends React.Component<{}, void> {
  render() {
    return <div />;
  }
}
```

(TypeScript 2.0.10 with `"strictNullChecks": true`)

**Comment by tkrotoff** [comment] 2016-11-18 13:04
Since the .d.ts files are generated from Mobx source code, the best would be to "port" Mobx from TypeScript 1 to TypeScript 2 and `strictNullChecks`. I've tried but I don't have the knowledge to fix the errors reported.

**Comment by mweststrate** [comment] 2016-11-18 19:21
@tkrotoff this is a known issue indeed, using `{}` instead of `void` should fix it. 

This issue is a duplicate of https://github.com/mobxjs/mobx-react/issues/97

Feel free to re-open that issue if there is no acceptable answer. Closing this one as duplicate

**Closed by mweststrate** 2016-11-18 19:21 UTC
