### ISSUE TITLE
Properties leaking across prototype chain when parent is observable

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [mobxjs/mobx#1092] opened 2017-07-11 15:12 UTC
I have a:

2. [x] Issue:
* [x] **Provide error messages including stacktrace**
There is no error. Just wrong behavior.
    * [x] Provide a **minimal** sample reproduction.
Since this is a **minimal** repro and does not require react I did not use the template provided. 
Here is the repro: https://runkit.com/guillaumeleclerc/runkit-npm-mobx/2.0.0
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
In the example I gave, `foobar` is created from `foo` but has no relation with `bar`. Suprisingly, as we can see from the output of the code it shares the property `c` with bar.

The expected behavior can be seen here https://runkit.com/guillaumeleclerc/runkit-npm-mobx/2.0.1. In this snippet, `foo` is not observable and everything behaves correctly.
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
As we can see from the snippet it uses node `v6.9.2` and mobx `3.2.1`

**Comment by urugator** [comment] 2017-07-12 20:00
I think it's a known limitation, caused by the fact that mobx uses a private property `$mobx` as a storage for values, interceptors etc.
It's probably solvable, but not trivially. Currently if `$mobx` exists on extended object (even only on prototype), it's simply used for new definitions (therefore everything is actually defined on prototype).
So in case the `$mobx` is defined only on prototype, a new `$mobx` object, which sort of *delegates to* the prototype's `$mobx` object, would have to be created. Naive pseudocode:
```javascript
if (target["$mobx"] && !target.hasOwnProperty("$mobx")) {
  // only target's prototype is observable   
  const values = Object.create(target["$mobx"].values); // create new "values" delegating to "$mobx.values" 
  target["$mobx"] = Object.create(target["$mobx"]); // create new "$mobx" delegating to "$mobx"
  // <- in reality a different delegating mechanism would have to be probably used instead of prototypical inheritance   
  target["$mobx"].values = values;        
  target["$mobx"].target = target;  
}
```
Note it's just my personal understanding, it may be a complete nonsense :)

**Comment by mweststrate** [comment] 2017-07-13 13:50
`extendObservable` at the moment only supports working with instances, not prototypes. (To define observable props on a prototype you could use `@observable` decorator (in ES5 syntax if needed: `observable(foo, "c", { value: 3 })` or something like that)

This maybe can be fixed by only reading `.$mobx` from ownProperties. Although I can imagine that leads to other problems as well, but that could be tried. But note that in that case you probably still often don't have the desired behavior, extendObservable on a propotype would introduce a static / shared observable property in the prototype, not an observable property unique for each instance. So the useful ness of that would be very limited (because for intentional static observable properties one would define the properties on the constructor, not on the prototype)

**Comment by GuillaumeLeclerc** [comment] 2017-07-13 14:19
I also thought that reading "ownProperties" made sense but I was not sure if there was other implications.

Static observable properties is exactly what I wanted. I want static on the prototype and per instance on the instances. The issue in this case is everything becomes static which is a huge problem for me.

**Comment by mweststrate** [comment] 2017-07-13 18:38
Feel free to try. If the test suite passes with the change I am confident this is a viable route :)

For static observables afaik the following should work:

```
function Foo() {
   extendObservable(this, { a: 1 }) // instance observables
}

extendObservable(Foo, { b: 2})

const x = new Foo()
x.a // 1
x.b // undefined
Foo.a // undefined
Foo.b // 2
```

**Comment by GuillaumeLeclerc** [comment] 2017-07-19 20:02
I will try to implement a PR tonight and see if I manage to get something that passes the tests

**Comment by GuillaumeLeclerc** [comment] 2017-07-19 22:25
I think it should be fine. Any feedback ?

**Closed** 2017-07-27 14:09 UTC
