### ISSUE TITLE
Gets undefined when accessing through the Mobx store

### ISSUE THREAD

**Issue by aamupadi1** [mobxjs/mobx#1337] opened 2018-02-02 19:34 UTC
I am trying to access the value of json object fetched from the server. The contents of the json is like this:

    {
        "id": 1,
        "property_photos": [
            {
                "image_thumbnail": "http://dev.site.com/media/CACHE/images/asdf/24f7d09a44a89e97ae28040bdb0fc059.jpg"
            },
            {
                "image_thumbnail": "http://dev.site.com/media/CACHE/images/sss/656a4131b9201baebb4d0de247c39519.jpg"
            },
        ],
        "address": {
            "url": "http://dev.site.com/places/api/locations/1/",
            "name": "Kenya"
        },
        "title": "3 BHK flat available",
    }

I am using mobx as my store. When I access the value from the response data, I can access without an error. However, after I pass the reponse data to the store and try to access the value from the store, I get errors 

> TypeError: undefined is not an object

I have list out the code that works from the respose data, also when I try to access the data from the store. Could you please help me out.

Code:

    @inject('PropertyStore') @observer
    export default class FeedList extends React.Component {
        componentDidMount() {
            this.fetchProperties()
        }

        fetchProperties = () => {
            const {PropertyStore} = this.props
            axios.get('http://local/api/properties/')
                .then(function (response) {
                    console.log('response data0.title', data[0].title)  // Works
                    console.log('response data0.address', data[0].address)  // Works
                    console.log('response data0.address.name', data[0].address.name)    // Works
                    console.log('response data0.property_photos[0]', data[0].property_photos[0])    // Works
                })
        }

        _renderItem = ({item}) => {
            return <FeedCard/>
        }

        render() {
            const {PropertyStore} = this.props
            console.log('PropertyList[0].title', PropertyStore.PropertyList[0].title)   // Works
            console.log('PropertyList[0].address', PropertyStore.PropertyList[0].address)   // Works
            console.log('PropertyList[0].address.name', PropertyStore.PropertyList[0].address.name) // DOES NOT work
            console.log('PropertyList[0].property_photos', PropertyStore.PropertyList[0].property_photos)   // Works
            console.log('PropertyList[0].property_photos', PropertyStore.PropertyList[0].property_photos[0])    // DOES NOT work
            return (
                <View style={styles.container}>
                    <FlatList
                        data={PropertyStore.PropertyList}
                        renderItem={this._renderItem}
                    />
                </View>
            )
        }
    }

**Comment by jamiewinder** [comment] 2018-02-05 09:31
Hard to tell for sure as a lot of code seems to be missing (for example, you're fetching but you aren't setting the response data anywhere on your example). All of your MobX store code is missing too.

But it looks to me like your component simply isn't handling the situation where the data hasn't loaded yet? When you say the other properties 'work', do you mean they actually have data or you can access them without errors (because I'd expect you to be able to access the shallow properties, but they'd be `undefined` meaning you'll only get errors on the deep properties).

**Comment by mweststrate** [comment] 2018-02-27 11:03
Closing for the lack of a decent issue reproduction

**Closed by mweststrate** 2018-02-27 11:03 UTC
Labels: issue-lacks-relevant-information
