### ISSUE TITLE
decorate utility doesn't work with strict mode enabled

### ISSUE THREAD

**Issue by rumer94** [mobxjs/mobx#2268] opened 2020-01-27 23:23 UTC
* [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. 
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

## Issue
On version `mobx 5.15.3`  using strict mode `enforceActions: "always"`  when I initialize a property and use the `decorate` utility to define it as an observable it throws an error as if I was changing the property outside an action.
On version `mobx 4.1.0` the application runs without errors
## The Code
You can find the sample [here](https://codesandbox.io/s/minimal-mobx-react-project-p5b31?fontsize=14&hidenavigation=1&theme=dark)

If I use the `@observable` decorator there is no error

`configure({ enforceActions: "always" });`

`class AppState {`
`@observable text = "HELLO";`
`}`

However, if I use the `decorate` utility it throws an error
`configure({ enforceActions: "always" });`

`class AppState {`
`text = "HELLO";`
`}`

`decorate(AppState, {`
`  text: observable`
`});`

## Error Messages
`Error
[mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: AppState@17.text`

## Expected behavior
Mobx should throw the error only if the observable property is changed outside an action, not when it's initialized.

**Comment by FredyC** [comment] 2020-01-27 23:38
Can you please try with `5.15.2`? There were some bigger internal changes and some bugs might have find its way there.

Also, reproduction would be nice with eg. CodeSandbox

**Comment by rumer94** [comment] 2020-01-27 23:41
> Can you please try with `5.15.2`? There were some bigger internal changes and some bugs might have found its way there.
> 
> Also, reproduction would be nice with eg. CodeSandbox

I added the codesandbox link

**Comment by rumer94** [comment] 2020-01-28 00:51
> Can you please try with `5.15.2`? There were some bigger internal changes and some bugs might have found its way there.
> 
> Also, reproduction would be nice with eg. CodeSandbox

I updated the sample with `5.15.2` and it throws the same error
[CodeSandbox sample](https://codesandbox.io/s/minimal-mobx-react-project-p5b31)

**Comment by urugator** [comment] 2020-01-29 18:43
This may need to be wrapped in `allowStateChanges`, not sure, you can give it a try
https://github.com/mobxjs/mobx/blob/582a51691ebdbb5b8cd628ee286919a6dafc480c/src/v5/api/observabledecorator.ts#L40

**Comment by mweststrate** [comment] 2020-02-10 10:15
The premise of this issue is wrong:

> Mobx should throw the error only if the observable property is changed outside an action, not when it's initialized.

In strict mode `always` all state initialization and construction should be done as part of actions: https://mobx.js.org/refguide/api.html#enforceactions:

> "always": State always needs be updated (which in practice also includes creation) in actions.

The bug here is basically that the first one doesn't throw, rather than that the second one does throw. 

(n.b., duplicate of https://github.com/mobxjs/mobx-react/issues/828#issuecomment-583720936, so the documentation / error message here might benefit from clearer documentation)

**Comment by urugator** [comment] 2020-02-10 14:11
@mweststrate

This works:
```javascript
configure({ enforceActions: "always" });

class AppState {
  @observable text = "HELLO";
}

const appState = new AppState();
```
This throws:
```javascript
configure({ enforceActions: "always" });

class AppState {
  text = "HELLO";
}
decorate(AppState, {
  text: observable
});

const appState = new AppState();
```
The behavior shouldn't differ imo.

**Comment by mweststrate** [comment] 2020-02-10 14:30
Ideally not, but the last one is the most consistent one, and the only one
truly consistently enforceable. However, changing the first one to the last
will probably cause a lot of trouble all over the world :)

**Comment by seivan** [comment] 2020-04-21 08:15
@urugator I generally use your second approach as it looks like decorators might(?) be going away. 

I find that wrapping the *initial* state within  a `runInAction` does the trick. 

```ts
class AppState {
  text: string
 constructor(text: string) {
    this.text = text
 }
}
decorate(AppState, {
  text: observable
});

const globalStore = runInAction(() => { return new AppState("HELLO") } ) 

Since every new nested observable "instance" created will be driven by an `action`, their constructors will work fine. 

```ts
class Todo {
  text: string
  constructor(text: string) {
    this.text = text
  }
}
decorate(Todo, {
  text: observable
});

class AppState {
  text: string
  todo: Todo
  constructor(text: string) {
    this.text = text
  }
  setTodo = (text: string) => {
    this.todo = new Todo(text)
  }
}
decorate(AppState, {
  text: observable,
  todo: observable
  setTodo: action
});
```

Though not sure how it will work with unit tests.

**Comment by mweststrate** [comment] 2020-07-10 21:34
Decorate doesn't exist anymore in v6, so closing

**Closed by mweststrate** 2020-07-10 21:34 UTC
Labels: bug, documentation, help wanted
