### ISSUE TITLE
Idea: Add option to disallow multiple Mobx versions at the same page

### ISSUE THREAD

**Issue by jhuiting** [mobxjs/mobx#1098] opened 2017-07-14 09:07 UTC
Idea:
  * [x] What problem would it solve for you? We ran into issues last week because two versions of Mobx were running on the same page. We'd like to just throw an error if that's the case to make sure the versions in sync.
  * [x] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)? Yes, can imagine that some people ran into the same problems. Might also be that people need multiple versions, hence the introduction of a switch to opt-in on this.
  * [x] Are you willing to (attempt) a PR yourself? Yes, no problem.
 
So when this option is set in the Mobx config it will throw an error instead of the warning you'd currently get.

**Comment by rasdaniil** [comment] 2017-07-25 23:40
3.2.0 introduced a warning about multiple instances, according to docs

**Comment by jhuiting** [comment] 2017-07-26 06:28
Yes, see also the last line of my issue ;-) I'm proposing now to optionally make that an error.

**Comment by mweststrate** [comment] 2017-09-18 11:53
I'll think there are already too much options around sandboxing / non sandboxing, sharing state etc as it is. I'm fine by printing an error instead of a warning to the console. Actually throwing however sounds as a breaking change, which we could do in the 4.0 release.

**Comment by phiresky** [comment] 2017-11-22 00:39
This issue also occurs when doing this:

```ts
import { observable } from "mobx/lib/mobx";

import { observable as o2 } from "mobx";

console.log(observable === o2);
```

when using es6 modules. The problem is that the VS Code autofix for importing missing variables does the first import, which imports a second copy (mobx.js) while `from "mobx"` loads mobx.module.js

**Comment by mweststrate** [comment] 2018-02-27 10:21
From Mobx and upward 4 this will be an error, so closing the issue here :)

**Closed by mweststrate** 2018-02-27 10:21 UTC
