### ISSUE TITLE
Mobx autorun is synchronous normally, but becomes non-synchronous when an action is running

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx#1911] opened 2019-02-24 21:12 UTC
I'd just like to document this clearly and understand it so I'm sure what's happening. It seems that reactions/autoruns typically will run synchonously:

```
let x = 0
let y = observable.box(1)
autorun(() => {
  x = y.get()
})
console.log(x) // 1
```

But there seems to be a way to disable this synchonicity, and it has something to do with batching/transactions.

```
let x = 0
let y = observable.box(1)
let z =  action(() => {
  console.log('doing something, not sure exactly what causes this behavior')
})
autorun(() => {
  z() // does this cause it?
  x = y.get()
})
console.log(x) // 0
```

I should really play with a test case and make the code above proper as it isn't proper. But this behavior caused me a bit of confusion.

My big ask would be, is there some way to prevent this from happening? I assume this has to do with preventing stale reads, but all my actions are sync as well, so I'd expect everything to be resolved in sync. I'm not really sure what's causing this exactly, so understanding there would be helpful.

**Comment by ItamarShDev** [comment] 2019-02-24 22:06
seems to work fine here: https://codesandbox.io/s/q92r0q324j?fontsize=14

**Comment by urugator** [comment] 2019-02-25 09:50
Take a look at https://github.com/mobxjs/mobx/issues/1006

**Comment by mayorovp** [comment] 2019-02-25 14:03
I cannot reproduce this:

```javascript
let x = 0
let y = observable.box(1)
let z =  action(() => {
  console.log('doing something, not sure exactly what causes this behavior')
})
autorun(() => {
  z() // does this cause it?
  x = y.get()
})
console.log(x) // 1
```

**Comment by natew** [comment] 2019-02-25 17:26
I was hoping someone would have a better understanding of *what* causes it
actually, that code does not but in my exploration something like it does.

It’s happening during the startup of a large app, and so it’s hard for me
to isolate it as it’s a pre-condition to where I can put a debugger.

I saw another ticket here about cases where autorun won’t be synchronous
though, I’ll find the link later. It’s definitely happening. I’ll attempt
to create a replication properly soon.

**Comment by mweststrate** [comment] 2019-03-14 09:49
Closing for lack of reproduction

**Closed by mweststrate** 2019-03-14 09:49 UTC
Labels: cannot reproduce
