### ISSUE TITLE
[Idea] Maintain and publish mobx 4 & 5 from the same branch

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx#2120] opened 2019-09-21 21:09 UTC
I can't say i know mobx codebase very well,
But as what i've seen most of the code of 4 & 5 is very similar,
The difference is mostly the proxy part.

What if struct the code in a way that only the different parts will be behind a build flag (or even runtime flat if the developer wishes)
And keep all of the code on master.
Another idea, that i'm not sure if will work:
Use monorepo, one package will be 4.x  and the other 5.x, and the shared code will be in a shared package (That won't be published, but will be bundled)
 
Kinda related #1957

**Comment by FredyC** [comment] 2019-09-22 09:36
Monorepos are the pain, mainly because there are no solid tools to with them (Lerna is crap).

Merging codebase does sound appealing, but I can imagine it would make code fairly messy even with build flags. Not sure really. If you are willing to give it a try, it could be really interesting and easing the maintenance pain toward the future.

**Comment by Bnaya** [comment] 2019-09-23 12:02
The initial idea is to keep publish V4 & V5,
just from the same branch (with separate package.json, or writing the version on the fly before publish),
And build/bundle flags will produce the correct bundle before each publish.
I believe i will find time to POC it after #2079 will get finalized

**Comment by mweststrate** [comment] 2019-10-02 11:18
Separate subpackages in the same branch sounds fine to me, if it isn't confusing for new contributors. Mixing code bases is a real pain. I tried, so I can confirm that it at least is not easy :).

**Comment by Bnaya** [comment] 2019-10-02 11:25
My personal experience from my last PR, even a small PR to both of the branches was confusing.

Have you tried that with mobx or other projects?

**Comment by FredyC** [comment] 2019-10-02 11:29
> Separate subpackages in the same branch sounds fine to me, if it isn't confusing for new contributors.

I can imagine it could be confusing for reviews to basically see changes two times in there.

> Mixing code bases is a real pain. I tried, so I can confirm that it at least is not easy :).

Not easy but also not impossible I assume? I kinda agree it would be the best way if it can work out somehow.

**Comment by mweststrate** [comment] 2019-10-02 11:30
mobx-state-tree packages multiple projects in the same repo. Works pretty
smooth (I'm generally in favor of mono repo's and single branches of work,
as it makes coordination so much easier, so I do think it is a good idea :))

**Comment by mweststrate** [comment] 2019-10-02 11:32
> I can imagine it could be confusing for reviews to basically see changes
two times in there.

Agreed, but I think in the PR template we can signal that the change
initially should only be made to the mobx5 one, until approved, and then
backporting can be done (in same PR), but that reduces burden for both
reviewer and submitter, as that last part can be glanced over.

With the docs in there as well, this is gonna be a much much better setup
to land new things onto :)

**Comment by FredyC** [comment] 2019-10-02 11:37
I really don't have much (almost any) insight into the repo code base, but perhaps we could go a middle way and besides folders for V4 and V5, there could be a common one for code that is the same across those versions. Perhaps even restructure it to reuse as much as possible.

Personally, I am totally DRY guy, so any sort of copy&pasting makes me rather uneasy.

**Comment by FredyC** [comment] 2019-10-02 11:39
Also note, that with two different branches doing the diff is very easy. With both codebases in different folders, you cannot really do git diff, so that could make contributing somewhat harder.

**Comment by mweststrate** [comment] 2019-10-05 23:08
@Bnaya docs are now in the master branch, so that blocker is gone :)

I originally started with trying to do MobX 4 and 5 with a largely common code base. But that got a real big untangable mess very quickly. Imho clarity and maintainability are more important than dry :).

**Comment by Bnaya** [comment] 2019-10-20 22:02
Unfortunately i can't find the time to work on it.
i will close it for now.

**Comment by mweststrate** [comment] 2019-10-21 20:25
No problem! I'll reopen it, as I think it is a cool idea nonetheless, and I or somebody else could pick it up.

**Comment by mweststrate** [comment] 2020-04-01 19:08
This has been done by @FredyC, so closing!

**Closed by mweststrate** 2020-04-01 19:08 UTC
Labels: ready-to-be-implemented-by-volunteer
