### ISSUE TITLE
MobX binding fails after deleting property

### ISSUE THREAD

**Issue by vitalif** [mobxjs/mobx#1730] opened 2018-09-20 14:51 UTC
Hi,

I have an

2. [X] Issue:

With MobX 5 and React: MobX binding breaks after deleting the property.

The sample is here: https://codesandbox.io/s/7z0pxn9v7j

To reproduce the bug:
- change the first editbox, for example, to 12. The editbox value will change and you'll see "Modified" below.
- then change it back to 1. The editbox value will change again and you'll see "Not modified" below.
- then try to change it to 12 again. You'll see "Modified", but the editbox WON'T CHANGE.

To continue you can click "force update" and it will rerender the row by another property - after that the binding starts to work again.

**Comment by urugator** [comment] 2018-09-20 23:08
Simplified reproduction: https://codesandbox.io/s/n96xrm109l

**Comment by urugator** [comment] 2018-09-21 13:09
> I can`t understand your demo

1. Click few times on the first button to see that both observers are reacting properly to `o.a` modifications
2. Click the second button to delete prop `a` from `o`
3. Click again the first button to see that the observer subscribed for `o.a` is no longer reacting...

**Comment by leeseean** [comment] 2018-09-21 18:48
> > I can`t understand your demo
> 
> 1. Click few times on the first button to see that both observers are reacting properly to `o.a` modifications
> 2. Click the second button to delete prop `a` from `o`
> 3. Click again the first button to see that the observer subscribed for `o.a` is no longer reacting...

have you compiled the code to es5?

**Comment by vitalif** [comment] 2018-09-23 09:27
How does it matter?

**Comment by mweststrate** [comment] 2018-09-26 10:10
This behavior is working as intended:

1. `delete` will set the property to `undefined`, so that all observers receive an `undefined` value once, and then throws away the observable. (after all, if we would keep it, we wouldn't delete it and always keep it around in memory, defeating the purpose)
2. once you reassign to `a`, it creates a _fresh_ field and observable (in javascript object terms, a _new_ property descriptor is added to the object, the old one isn't revived). In other words, it is a new property, that just happens to have the same name another property had earlier
3. This is however not a change to the `a` property, it is a property _addition_ to the `o` object. 
4. your component is not observing property additions / removals, so it wont know about this new property, ignoring re-renders
5. you _could_ listen to all property additions / removals, by for example using the `keys` (or `toJS` which internally uses `keys`) utility from mobx, or even for a specific one using `has`
6. As is demonstrated in this code sandbox: https://codesandbox.io/s/724zqrxpw1
7. Which shows that `has` doesn't react properly, so that actually is a bug, but a different one :-).

**Comment by urugator** [comment] 2018-09-26 10:31
@mweststrate 

> 4. your component is not observing property additions / removals, so it wont know about this new property, ignoring re-renders

How is it then possible that component observes the first addition?  Notice that `o` is initialized empty. On the first addition of prop `a`, the component is updated. But the consequent additions don't work that way...

**Comment by vitalif** [comment] 2018-09-26 11:01
+1. AFAIK that was mobx 4 that didn't handle dynamic objects. From reading the source it seems mobx 5 has all code required to observe property additions and removals.

I also tried to check the dependencies using trace() and they're the same at the beginning and at the end of the test.

**Comment by urugator** [comment] 2018-09-26 11:10
Perhaps it will start working properly when `.has` is fixed? Check the `get` impl:
https://github.com/mobxjs/mobx/blob/master/src/types/dynamicobject.ts#L32

**Comment by mweststrate** [comment] 2018-09-26 11:19
@urugator @vitalif good points, I think I am messing up MobX 4 vs MobX 5 behavior myself now :), will investigate further!

**Comment by mweststrate** [comment] 2018-09-27 12:42
Fixed in MobX 4.5.0 / 5.5.0

**Closed by mweststrate** 2018-09-27 12:42 UTC
