### ISSUE TITLE
Strict mode breaks stateless stores with classes variable initialisation

### ISSUE THREAD

**Issue by yann-stepienik-cko** [mobxjs/mobx#901] opened 2017-03-23 13:37 UTC
When creating a "stateless" store (Re-instanciated on navigation) in an App using metaconstructor attributes initialisation like so : 

    class store { 
         @Observable myVar  = 123; // Using Typescript-like compilers you can init your var here, outside of constructor.

         // other stuff..
    }

    // somewhere in my page : 

    new store();

Note that the issue remains the same if I do it the old way by initialising the var in the constructor itself (This is just a short hand).

The first time this code get renderer everything is ok, but as soon as you change page, the / new store() / gets hit again, and for some reason, even thought it theoretically instantiate a brand new store, Mobx's useStrict(true) mode report a mutation outside of an action; *Only on the second hit of new ..() *.
Is it an issue of the strict mode ?

**Comment by urugator** [comment] 2017-03-23 18:58
Strict mode reports only if an observable modified outside of an action is observed by something. That probably explains the *second hit*, because on the "first hit", the initial render haven't run yet, so there are no observers and therefore nothing to report.
Hard to say where the problem exactly is, maybe you could setup jsfiddle reproducing the issue?

**Comment by yann-stepienik-cko** [comment] 2017-03-24 10:15
Oh right that make more sense now, here is a Fiddle to reproduce the issue : 

See line 49.

https://jsfiddle.net/wv3yopo0/1054/

**Comment by urugator** [comment] 2017-03-25 09:59
Fiddle throws at line 53 because store.todos is modified outside of action while being observed by TodoListView. Line 49 should be fine.

**Comment by yann-stepienik-cko** [comment] 2017-04-05 09:39
Hmm you're right. 
I might have mis-identified the problem then, here is my store for more insight : 

https://pastebin.com/BSJqdmri

Then in my components I do : 

https://pastebin.com/LgNicSMN

When I render the component twice, the new Store() get executed again and  I get the error: 

![screen shot 2017-04-05 at 10 38 52](https://cloud.githubusercontent.com/assets/17568523/24699507/1656c8ae-19ec-11e7-9d8a-7a44ff0fcfbc.png)

**Comment by urugator** [comment] 2017-04-05 11:00
Don't see anything exactly wrong, but I would start by removing `@remotedev` and then wrapping `this.transactionsStore = new this.props.TransactionsStore();` into `runInAction`. Then I would remove everything which doesn't involve `indicatorsLoading`

> When I render the component twice

Do you mean rendering two  different component instances or the same component twice?

**Comment by yann-stepienik-cko** [comment] 2017-04-05 11:54
Okay, I'm gonna try doing this to see what might cause the issue.

> What Do you mean rendering two different component instances or the same component twice?

I basically have a page using transactionStore (see the code of the page on Pastebin) but when I change page and I come back (Im using React Router if that's relevant) I have the error.

> Which MobX version do you use?

I use 3.1.8

**Comment by mweststrate** [comment] 2017-10-05 19:08
This issue seems to have died a silent dead. Closing it. Feel free to revive if the problem still needs to be addressed.

**Closed by mweststrate** 2017-10-05 19:08 UTC
