### ISSUE TITLE
Proxy error despite disabling them at app start

### ISSUE THREAD

**Issue by hardcodet** [mobxjs/mobx#2642] opened 2020-11-25 01:41 UTC
I'm seeing a slightly weird issue after my migration from MobX 5 to 6

```
MobX 6.0.4
MobX React 7.0.5
React Native, Android 10 (iOS works)
Still using decorators
```

This code in my app root (`index.js`) works:

```
import { registerRootComponent } from 'expo';

import {configure} from "mobx";
configure({useProxies: "never", enforceActions: "never"})

import {FooApp} from './App2';
//import {App} from "./App";
```

FooApp is just a very simple view that uses an observable view model. Now, as soon as I uncomment the import for the real app, I'm getting "Proxy objects are not available in the current environment. Please configure MobX to enable a fallback implementation.". Even though I clearly did just disabled them a line above.

If I copy the `configure`-line on top of my root store, the error is gone. So it looks like
- that whatever context is loading that view model doesn't seem to be using the same config that was declared at the app root
- or that configuration was lost/reverted somehow

The problem is that I have no idea *why* the issue happens in the first place (threading issue, or MobX simply reconfiguring itself in certain cases). I double and triple checked - I'm not configuring MobX anywhere else, so that my code would have reverted that setting is out of the question.

**Comment by FredyC** [comment] 2020-11-25 07:32
Can you please setup a minimal reproduction repo?

**Comment by hardcodet** [comment] 2020-11-25 15:41
@FredyC  I managed to get one. Maybe it has to do with my understanding of JavaScript imports. Here's my index:

```
import { registerRootComponent } from 'expo';

// back out of mobx proxies, which aren't support in React Native
import {configure} from "mobx";
configure({useProxies: "never", enforceActions: "never"})

// import AFTER the mobx configuration
import {FooApp} from './App2';

registerRootComponent(FooApp);
```

I assume that the configuration becomes active before I'm importing anything.

Now, note the view model that sits on top of my `FooApp.tsx`, specifically the **export** right at the end of the class declaration. If I comment out the export, and only construct a `Foo` within the `FooApp`, the error doesn't occur. It appears that this instance is being created _before_ the mobx configuration. Also, if I just redeclare the mobx configuration there, the error is also gone. I still don't really understand this...


```
class Foo extends LogEnabled {
    @observable name = "hello philippe"

    @observable names: string[] = []; //observable.array([], {deep: false});

    @computed
    get hasNames() {
        return this.names?.length > 0;
    }

    constructor() {
        super();
        makeObservable(this);
    }
}

// RE-DECLARING THIS CONFIG BLOCK ALSO FIXES THINGS
// import {configure} from "mobx";
// configure({useProxies: "never", enforceActions: "never"})

// THIS CAUSES THE RUNTIME CRASH. COMMENTING IT OUT FIXES THINGS
export const fooInstance = new Foo();


export const FooApp = observer(() => {
    // THIS IS NOT A PROBLEM
    const [vm] = useState(new Foo());

    return (
        <View>
            ...
        </View>
    )
});
```


ps: Fast Refresh was not my friend. One really has to manually reload the app in order to get reliable errors/failures.

**Comment by mweststrate** [comment] 2020-11-25 16:02
Duplicate of https://github.com/mobxjs/mobx/discussions/2607. Avoid top level creation of observables or reorder your import statements. Import reordering has really unpredictable results, top level statement reordering / wrapping them in a func is usually the solution.

**Comment by hardcodet** [comment] 2020-11-25 16:22
@mweststrate  Actually, the issue still persists if I remove everything observable from my root store (which in turn just declares stores with observables). Moving the MobX config from the app root to the root store fixes things, so I'm good with that.

```
// back out of mobx proxies, which aren't support in React Native
import {configure} from "mobx";
configure({useProxies: "never", enforceActions: "never"})

export class RootStore {

    uiStore: UIStore;
    messenger: Messenger;

    constructor() {
        this.messenger = new Messenger();
        this.uiStore = new UIStore();
        ...
    }
}


/**
 * Our global root store.
 */
const rootStoreInstance: RootStore = new RootStore();
```

**Closed** 2020-11-25 16:26 UTC
Labels: ♺ needs-reproduction, 🐛 bug
