### ISSUE TITLE
Typescript + Mobx observable([]).remove(...)

### ISSUE THREAD

**Issue by wildeyes** [mobxjs/mobx#669] opened 2016-11-19 08:42 UTC
I am getting a 
```
ERROR in [default] /edit.tsx:80:47
Property 'remove' does not exist on type 'string[]'.
```
with mobx@2.6.2, webpack with awesome-typescript-loader@2.2.4 and typescript@2.0.8.

**Comment by benjamingr** [comment] 2016-11-23 13:41
Can you show a full example I can't show.

**Comment by JabX** [comment] 2016-11-24 23:33
This looks weird, since `observable()` has no signature that returns a vanilla array.

But if you're using it as a decorator (`@observable list = []`), then it's to be expected since the decorator doesn't change the type of the property, meaning that even if at runtime `list` is an `ObservableArray` (which has the `remove()` method), at compile time it's still going to be considered as an array. In that case, your only option is an explicit annotation.

**Comment by mweststrate** [comment] 2016-11-27 08:59
Closing for the lack of a reproduction

**Closed by mweststrate** 2016-11-27 08:59 UTC
Labels: needs investigation

**Comment by mkozhukharenko** [comment] 2016-12-24 09:40
@mweststrate 
this example couses an error
```
class Todo {
  store: TodoStore
  value: string

  constructor(store: TodoStore, value: string) {
    this.store = store
    this.value = value
  }

  @action destroy() {
    this.store.remove(this)
  }
}

class TodoStore {
  title: string = 'TEST'
  @observable todos: Todo[]

  constructor(title: string) {
    this.title = title
    this.todos = [new Todo(this, 'test')] 
  }

  @action removeWord(word: WordModel) {
    this.todos.remove(word) // Property 'remove' does not exist on type 'Todo[]'.
  }
}
```

but if we set todos to IObservableArray everything works
```
class TodoStore {
  title: string = 'TEST'
  @observable todos: IObservableArray<Todo>

  constructor(title: string) {
    this.title = title
    this.todos = [new Todo(this, 'test')] as IObservableArray<Todo>
  }

  @action removeWord(word: WordModel) {
    this.todos.remove(word)
  }
}
```

Is it ok to write like this?

**Comment by JabX** [comment] 2016-12-25 11:46
Yup that's how you should do it. 

But I'd rather do something like this instead:
```ts
class TodoStore {
  title: string = 'TEST'
  readonly todos = observable<Todo>([])

  constructor(title: string) {
    this.title = title
    this.todos.push(new Todo(this, 'test'));
  }

  @action removeTodo(todo: Todo) {
    this.todos.remove(todo)
  }
}
```

This way you have no array annotation and you prevent any array reassignment  by marking it readonly (you don't need an `@observable` decorator if you don't do reassignment). Use `ObservableArray.replace()` instead if you want to "create" a new array.

**Comment by mkozhukharenko** [comment] 2016-12-25 18:25
@JabX  it makes sense.
thank you very much!

**Comment by ehartford** [comment] 2017-02-01 18:00
This goes against the point of the @observable annotation...  
If I annotate an array with @observable, typescript should treat it as ObservableArray.
Is there no way to do this with @types/mobx?

**Comment by mweststrate** [comment] 2017-02-02 09:01
@ehartford yes there is since Mobx 3, use

`readonly todos = observable.array([])`

**Comment by JabX** [comment] 2017-02-02 10:06
An annotation cannot change the type of the property (or class, or method) it is applied to, and I believe it to be the case for all the languages I know of.

**Comment by ehartford** [comment] 2017-02-02 17:18
@JabX  The annotation does, in fact, at runtime, change the type from a native array into an ObservableArray.  It's just a question of whether TypeScript is aware of the change and able to provide correct dev-time and compile-time validation.  If TypeScript doesn't give us the tools to describe the change, then it's a TypeScript bug.  If we can describe it but we aren't, it's bug in the MobX typings.

**Comment by JabX** [comment] 2017-02-03 09:21
@ehartford I was talking about compile-time type information, sorry for the inaccuracy. Sure, it does indeed change the type at runtime, which I consider to be a bad practice in general because of the impossibility of describing it at compile-time.

Just don't use the annotation if need the type info, @mweststrate's solution (which was also what I proposed a few posts earlier) is better anyway.

**Comment by stevematdavies** [comment] 2019-02-04 07:20
I cant follow this, I'm getting the same error as given above, and I'm simply observing an array of strings:
```
....
questionQueue = string[];
...
decorators(MyClass, { questionQueue: observable })
```
This is just a number of typescript and MObX issues I'm having, when trying to stick to the docs.
