### ISSUE TITLE
Make observables used in computed value watched even if not used in last computation

### ISSUE THREAD

**Issue by ugros** [mobxjs/mobx#613] opened 2016-10-15 14:16 UTC
Hello, I created a SO question a few days ago, but I didn't get any answers.
Maybe I could get any help or suggestion here?

SO question: http://stackoverflow.com/questions/39986495/make-observables-used-in-computed-value-watched-even-if-not-used-in-last-computa

Thanks

**Comment by mweststrate** [comment] 2016-10-15 14:21
@ugros You can use `observe` from `mobx` or `keepAlive` from `mobx-utils` to keep an observable alive. But I think the interesting question is, why do you want to keep it alive if it is not relevant for the computed value at this point?

Conditions in computed values are perfectly sane, the fact that observables are temporarily de-observed if not in active usually results in significant performance gains; if `condition` is true, the array length doesn't influence the outcome, hence mobx won't even attempt to re-run your computation

**Comment by mweststrate** [comment] 2016-10-18 11:15
Closing question for now, this is intended behavior. If it is still unclear, feel free to re-open

**Closed by mweststrate** 2016-10-18 11:15 UTC
Labels: question
