### ISSUE TITLE
[v6] Cannot decorate ... the property is already decorated as observable

### ISSUE THREAD

**Issue by olee** [mobxjs/mobx#2457] opened 2020-09-22 15:31 UTC
Using mobx 6.0.0-rx8 with the following decorator-based code will throw this exception:
`[MobX] Cannot decorate 'value1': the property is already decorated as observable`

```ts
class BaseClass {

    @observable
    value1?: number;

    constructor() {
        makeObservable(this);
    }

}

class SubClass extends BaseClass {

    constructor() {
        super();
        makeObservable(this);
    }

    @computed
    get value1Computed() {
        return this.value1;
    }

}

new SubClass();
```

After debugging the code I found out that it is related to [this code](https://github.com/mobxjs/mobx/blob/c5b268081a6f0f30e4912821e6a736a2d5a1726b/src/api/decorators.ts#L76-L80)
```ts
                    if (!hasProp(target, key) && !hasProp(current, key)) {
                        // not all fields are defined yet, so we are in the makeObservable call of some super class,
                        // short circuit, here, we will do this again in a later makeObservable call
                        return true
                    }
```

This check fails, if the subclass only contains computed properties and no single observable variable.

Modifying `SubClass` by adding a simple observable value indeed removed the exception:
```ts
class SubClass extends BaseClass {

    @observable
    value2?: number;

    constructor() {
        super();
        makeObservable(this);
    }

    @computed
    get value1Computed() {
        return this.value1;
    }

}
```

Another smaller issue I noticed is that in development bundles with webpack the minified file `mobx.es.js` was used which makes debugging these kinda things difficult.
I had to go into package.json and remove the module entry to get an unminified build for debugging.

Also (but this might be related to some issue in my webpack config) the source maps for the cjs build was not working properly for me.

**Comment by mweststrate** [comment] 2020-09-22 17:54
Good catch and thanks for the analysis! Will make sure this gets fixed before the release.

**Comment by mweststrate** [comment] 2020-09-24 21:27
Pushed a fix, thanks for reporting!

**Closed** 2020-09-24 21:27 UTC
Labels: bug

**Comment by olee** [comment] 2020-09-24 23:50
I saw your fix and I think I still know a way to break it :D
Just wanted to write this here as a reminder for now for me as well, because I don't have time to test my guess right now (will probably do it when a new npm release is out)

**Comment by akphi** [comment] 2020-10-01 07:09
@mweststrate Just want to check if this is intended behavior in v6. But I'm seeing error now for this case

```typescript

abstract class Animal {}
class Dog extends Animal {}

class BaseClass {
    @observable value1: Animal;

    constructor() {
        makeObservable(this);
    }
}

class SubClass extends BaseClass {
    @observable value1: Dog;

    constructor() {
        super();
        makeObservable(this);
    }
}
```

I'm getting the same error `Cannot decorate 'value1': the property is already decorated as observable`

**Comment by olee** [comment] 2020-10-01 22:54
You can just not add the @observable attribute to value1 in SubClass and it might work ... or you might have to do it the other way round ... not sure.
Otherwise you can still use a generic in the base class as an alternative.

**Comment by mweststrate** [comment] 2020-10-02 13:21
@akphi TypeScript has special syntax for refining the type of a property without redeclaring it; use `declare value1: Dog` instead. [Playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUgBAXAngBwKYBNUDNIG8DyARgFaoDG8AvpGQPYB2AzvFCMOOKBNHEmjQ2at24MgBsAho0aQAgvQCWAWwli8HSh3FSZAYQnxIqAB7xU9dDPnLV6yPchLUtAO4AKAJTqoDzZtGS0pAAErROdg4SiipiAPwAXHLRtgC8kACuFtgK9BgA3OD+2kH68KHhJmYWMuWoEfaY2gBOdVE2YomlBUWChmQGtZBpuS6QpbWeBf1lYagAdG0xc06uk0A)
