### ISSUE TITLE
Unable ro resolve module from mobx

### ISSUE THREAD

**Issue by sepehrooo** [mobxjs/mobx#403] opened 2016-07-09 11:09 UTC
<img width="376" alt="screen shot 2016-07-09 at 5 39 17 am" src="https://cloud.githubusercontent.com/assets/2351478/16707649/3598f8ac-45eb-11e6-9900-6a413b4b5207.png">
<img width="1060" alt="screen shot 2016-07-09 at 5 39 22 am" src="https://cloud.githubusercontent.com/assets/2351478/16707650/35a02d16-45eb-11e6-9e2a-bdad43e8c21d.png">

I get these 2 errors and I don't know why...
I did npm install in my react-native folder. but still I get this error.
Please help.

**Comment by mweststrate** [comment] 2016-07-09 22:34
I presume you already tried the suggested steps. Did you check whether `mobx` is in your node_modules folder (or the node_modules folder of react-komposer) after `npm install`? Maybe @markoshust is familiar with the above error. I suspect this issue can best be filed at react-komposer if the above things didn't help, doesn't seem to relate to mobx itself, but more probably to the dependency configuration of react-komposer.

**Comment by markoshust** [comment] 2016-07-10 01:03
Make sure you are on react-komposer 1.13.1. It looks like arunoda made a subsequent release to include mobx. https://github.com/kadirahq/react-komposer/commit/8ae210ed476bb26976f60ef35d94038e16f04868

**Comment by mweststrate** [comment] 2016-07-12 09:31
@sepehrooo did that fix the issue?

**Comment by mweststrate** [comment] 2016-07-13 14:56
Assuming that the issue is resolved by upgrading react-komposer. Feel free to reopen the issue if that isn't the case.

**Closed by mweststrate** 2016-07-13 14:56 UTC

**Comment by sepehrooo** [comment] 2016-07-13 15:23
@mweststrate Yes it worked. Sorry I responded a bit late. I was on a vacation.
Thanks a lot for helping out :)
