### ISSUE TITLE
version 3.1.6 breaks with error 'cannot set property 'struct' of undefined'

### ISSUE THREAD

**Issue by cong876** [mobxjs/mobx#888] opened 2017-03-14 11:47 UTC
Welcome to MobX. Please provide as much relevant information as possible!

I have a*:

1. [ ] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [ ] Issue:
  * [ ] **Provide error messages including stacktrace**
  * [ ] Provide as much **relevant code**, or, preferrably **create a reproduction based on this [JSFiddle](https://jsfiddle.net/mweststrate/wv3yopo0/)**: 
  * [ ] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [ ] State the versions of MobX and relevant libraries. Which browser / node / ... version?
3. [ ] Idea:
  * [ ] What problem would it solve for you?
  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)?
  * [ ] Are you willing to (attempt) a PR yourself?
 
Please tick the appropriate boxes. Feel free to remove the _other_ sections.

**Comment by mweststrate** [comment] 2017-03-14 11:52
duplicate of #887. Just unpublished. Thanks for reporting! We first have to sort this further out

**Closed** 2017-03-14 11:52 UTC

**Comment by duivvv** [comment] 2017-03-14 12:04
thanks for the fast action
