### ISSUE TITLE
Mobx 4.12.0 includes Set (Es6?)

### ISSUE THREAD

**Issue by Havunen** [mobxjs/mobx#2043] opened 2019-07-14 07:59 UTC
Mobx 4.12.0 is documented to run on any ES5 compliant browser, but the bundle in Mobx 4.12.0 includes ES6 `Set` which fails in IE10. 

https://travis-ci.org/infernojs/inferno/jobs/558177458

Mobx 4.8.0 works as expected. 

IE10 has 99% support of ES5 based on ES compatibility table here:
http://kangax.github.io/compat-table/es5/
The missing feature is related to enumerable. Is this documentation error or bug in code?

**Comment by FredyC** [comment] 2019-07-14 08:26
Well, you can polyfill Set (I recommend https://polyfill.io), but you are right it's not exactly ES5 compatible version in that case. I think we can get away with adding a note about using a polyfill. I doubt we want to rewrite lib for an obsolete platform.

As the side note, by the Q1 2020 the Windows 7 will become officially unsupported along with IE10/11. That's going to be a cause for celebration for sure :)

**Comment by mweststrate** [comment] 2019-07-17 19:15
Since this is mentioned in the docs already and further working as intended, closing this issue. https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#observablesetvalue-options

**Closed by mweststrate** 2019-07-17 19:15 UTC
Labels: documentation, ready-to-be-implemented-by-volunteer
